# DOUBLE CLICK THE PROBLEM CELL TO SEE THE CORRECT FORMAT OF THE PROBLEM AND EXPECTED OUTPUT

# START OF MODULE 4 - BROADCASTING AND ARITHMETIC OPERATIONS

BEGINNER LEVEL

Problem #1: Basic Array Addition
Create two 1D arrays: a = [1, 2, 3] and b = [4, 5, 6]. Add them together and print the result.

# Expected Output:
[5 7 9]

In [2]:
import numpy as np 

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = a + b 

print(c)

[5 7 9]


Problem #2: Scalar Broadcasting - Addition
Create a 1D array: [10, 20, 30, 40]. Add the scalar value 5 to every element and print the result.

# Expected Output:
[15 25 35 45]

In [3]:
import numpy as np 

arr = np.array([10, 20, 30, 40])

scalar_add = arr + 5 

print(scalar_add)

[15 25 35 45]


Problem #3: Array Subtraction
Create two 2x2 arrays: [[5, 6], [7, 8]] and [[1, 2], [3, 4]]. Subtract the second array from the first and print the result.

# Expected Output:
[[4 4]
 [4 4]]

In [7]:
import numpy as np 

arr1 = np.array([[5, 6],
                 [7, 8]])
arr2 = np.array([[1, 2],
                 [3, 4]])

sub = arr1 - arr2

print(sub)

[[4 4]
 [4 4]]


Problem #4: Scalar Multiplication
Create a 1D array: [2, 4, 6, 8]. Multiply every element by 3 and print the result.

# Expected Output:
[ 6 12 18 24]

In [9]:
import numpy as np 

arr = np.arange(2,9,2)

scalar_multi = arr * 3

print(scalar_multi)

[ 6 12 18 24]


Problem #5: Element-wise Multiplication
Create two 3-element arrays: [1, 2, 3] and [4, 5, 6]. Multiply them element-wise and print the result.

# Expected Output:
[ 4 10 18]


In [10]:
import numpy as np 

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

one_dimn_multi = arr1 * arr2

print(one_dimn_multi)

[ 4 10 18]


Problem #6: Array Division
Create two arrays: [10, 20, 30] and [2, 4, 5]. Divide the first array by the second element-wise and print the result.

# Expected Output:
[5. 5. 6.]

In [11]:
import numpy as np 

arr1 = np.array([10, 20, 30])
arr2 = np.array([2, 4, 5])

div_op = arr1 / arr2 

print(div_op)

[5. 5. 6.]


Problem #7: Broadcasting with Different Shapes
Create a 2D array: [[1, 2, 3], [4, 5, 6]] and a 1D array: [10, 20, 30]. Add them using broadcasting and print the result.

# Expected Output:
[[11 22 33]
 [14 25 36]]

In [15]:
import numpy as np 

arr1 =  np.array([[1, 2, 3],
                  [4, 5, 6]])

arr2 = np.array([10, 20, 30])

add_op = arr1 + arr2

print(add_op)

[[11 22 33]
 [14 25 36]]


Problem #8: Scalar Division
Create a 2x2 array: [[10, 20], [30, 40]]. Divide every element by 10 and print the result.

# Expected Output:
[[1. 2.]
 [3. 4.]]

In [16]:
import numpy as np 

arr = np.array([[10, 20], [30, 40]])

scalar_div = arr / 10 

print(scalar_div)

[[1. 2.]
 [3. 4.]]


Problem #9: Mixed Operations
Create an array: [1, 2, 3, 4]. Perform the operation: (array * 2) + 5 and print the result.

# Expected Output:
[ 7  9 11 13]


In [18]:
import numpy as np 

arr = np.array([1,2,3,4])

scalar_multi = (arr * 2) + 5
print(scalar_multi)

[ 7  9 11 13]


Problem #10: Broadcasting Row Vector
Create a 3x1 array: [[1], [2], [3]] and a 1x3 array: [[10, 20, 30]]. Add them using broadcasting and print the result.

# Expected Output:
[[11 21 31]
 [12 22 32]
 [13 23 33]]

In [20]:
import numpy as np 

arr_3_1 = np.array([[1], [2], [3]])
arr_1_3 = np.array([[10,20,30]])

print(arr_3_1 + arr_1_3)

[[11 21 31]
 [12 22 32]
 [13 23 33]]


Problem #11: Arithmetic with Array Attributes
Create a 2x3 array and a 1x3 array. Add them, then print the shape of the result.

# Expected Output:
(2, 3)

In [23]:
import numpy as np 

arr1 = np.arange(2*3).reshape(2,3)
arr2 = np.arange(1*3).reshape(1,3)

arr3 = arr1 + arr2 

print(arr3.shape)

(2, 3)


Problem #12: Division with Different Data Types
Create an integer array: [10, 20, 30] and divide by integer 3. Print the result and its data type.

# Expected Output:
[3.33333333 6.66666667 10.        ]
float64

In [24]:
import numpy as np 

int_arr = np.array([10, 20, 30])
scalar_div = int_arr / 3

print(scalar_div)
print(scalar_div.dtype)

[ 3.33333333  6.66666667 10.        ]
float64


Problem #13: Broadcasting with Reshape
Create a 1D array of 6 elements and reshape to 2x3. Create another 1D array of 3 elements. 
Multiply them using broadcasting and print the result.

# Expected Output:
[[ 0  1  4]
 [ 9 16 25]]

In [27]:
import numpy as np 

arr = np.arange(6).reshape(2,3)
arr2 = np.arange(3)

multi_op = arr * arr2 

print(multi_op)

[[ 0  1  4]
 [ 0  4 10]]


Problem #14: Compound Arithmetic Operations
Create arrays: a = [2, 4, 6] and b = [1, 2, 3]. Calculate (a + b) * (a - b) and print the result.

# Expected Output:
[ 3 12 27]


In [28]:
import numpy as np 

a = np.array([2, 4, 6])
b = np.array([1, 2, 3])

func_op = (a + b) * (a - b)

print(func_op)

[ 3 12 27]


Problem #15: Broadcasting with Slicing
Create a 4x4 array with values 1-16. Slice to get the first 2 rows, 
then add a 1D array [100, 200] using broadcasting (properly aligned).

# Expected Output:
[[101 102 103 104]
 [205 206 207 208]]

In [39]:
import numpy as np 

arr = np.arange(1, 4*4 + 1).reshape(4,4)
arr2 = np.array([100, 200]).reshape(2,1)
slices = arr[:2]

print(slices + arr2)


[[101 102 103 104]
 [205 206 207 208]]


Problem #16: Element-wise Power Operation
Create an array: [2, 3, 4]. Raise each element to the power of 3 and print the result.

# Expected Output:
[ 8 27 64]

In [40]:
import numpy as np 

arr = np.array([2, 3, 4 ])

scalar_power = arr ** 3 

print(scalar_power)

[ 8 27 64]


Problem #17: Broadcasting with Transpose
Create a 3x1 array and a 1x3 array. Multiply them after transposing one to make broadcasting work correctly.

# Expected Output:
[[ 0  0  0]
 [ 0  1  2]
 [ 0  2  4]]

In [ ]:
import numpy as np 

arr1 = np.arange(3*1).reshape(3,1)
arr2 = np.arange(1*3).reshape(1,3)

#TRANSPOSE arr1 
trans_arr1 = np.transpose(arr1)
trans_arr2 = np.transpose(arr2)
multi_op = trans_arr1 * trans_arr2

print(multi_op)


[[0 0 0]
 [0 1 2]
 [0 2 4]]


Problem #18: Arithmetic with Boolean Indexing
Create an array: [5, 10, 15, 20, 25]. Use boolean indexing to select elements greater than 10, 
then multiply the selected elements by 2.

# Expected Output:
[30 40 50]

In [49]:
import numpy as np 

arr = np.arange(5, 26, 5)
bool_mask = arr > 10 

multi_op = arr[bool_mask] * 2

print(multi_op)

[30 40 50]


Problem #19: Mixed Data Type Operations
Create an integer array: [1, 2, 3] and a float array: [1.5, 2.5, 3.5]. Multiply them and check the resulting data type.

# Expected Output:
[ 1.5  5.  10.5]
float64


In [50]:
import numpy as np 

int_arr = np.array([1, 2, 3])
float_arr = np.array([1.5, 2.5, 3.5])

multi_op = int_arr * float_arr

print(multi_op)
print(multi_op.dtype)

[ 1.5  5.  10.5]
float64


Problem #20: Comprehensive Broadcasting Example
Create a 2x3 array and a 3-element 1D array. Perform addition, multiplication, 
and division operations between them using broadcasting and print all results.

# Expected Output:
Addition:
[[ 1  3  5]
 [ 4  6  8]]
Multiplication:
[[ 0  2  6]
 [ 0  5 12]]
Division:
[[0.  2.  1.5]
 [0.  5.  3. ]]

In [71]:
import numpy as np 

arr = np.arange(1, 2 * 3 + 1).reshape(2,3)
arr2 = np.arange(3)

add_op = arr + arr2 
multi_op = arr * arr2 

mask = arr2 > 0

div_op = np.divide(arr, arr2, where = mask)


print("Addtion:")
print(add_op)
print("Multiplication:")
print(multi_op)
print("Division:")
print(div_op)


Addtion:
[[1 3 5]
 [4 6 8]]
Multiplication:
[[ 0  2  6]
 [ 0  5 12]]
Division:
[[0.  2.  1.5]
 [0.  5.  3. ]]


Part 11 
Date: 11/24/25
Total Problem Solved: 20
Time Spent: 2 hr and 30 mins

Topic Include: Broadcasting and Arithmetic Operations (Add, Subtract, Multiply, Divide, etc.)

Difficulty: Beginner(20)

START of Intermediate

Problem #1: Broadcasting with Reshape
Create a 1D array of 8 elements and a 2x4 array. Reshape the 1D array to be compatible for broadcasting along rows, then multiply them element-wise.

# Expected Output:
[[ 0  1  4  9]
 [16 25 36 49]]

In [2]:
import numpy as np

arr1 = np.arange(8)
arr2 = np.arange(8).reshape(2,4)

new1 = arr1.reshape(2,4)

multi_op = new1 * arr2

print(multi_op)

[[ 0  1  4  9]
 [16 25 36 49]]


Problem #2: Multi-dimensional Broadcasting
Create a 3x1x2 array and a 1x4x1 array. Add them using broadcasting and print the resulting shape and array.

# Expected Output:
Shape: (3, 4, 2)
Array:
[[[ 2  3]
  [ 3  4]
  [ 4  5]
  [ 5  6]]
 [[ 4  5]
  [ 5  6]
  [ 6  7]
  [ 7  8]]
 [[ 6  7]
  [ 7  8]
  [ 8  9]
  [ 9 10]]]

In [17]:
import numpy as np 

arr1 = np.arange(1, 7).reshape(3,1,2)
arr2 = np.arange(1, 5).reshape(1,4,1)

#Because the shapes are compatible, lets just add them directly

add_op = arr1 + arr2

print(f"Shape: {add_op.shape}")
print(f"Array: \n {add_op}")

Shape: (3, 4, 2)
Array: 
 [[[ 2  3]
  [ 3  4]
  [ 4  5]
  [ 5  6]]

 [[ 4  5]
  [ 5  6]
  [ 6  7]
  [ 7  8]]

 [[ 6  7]
  [ 7  8]
  [ 8  9]
  [ 9 10]]]


Problem #3: Arithmetic with Boolean Masks
Create a 2D array of random numbers between 0-10. Create a boolean mask for values > 5, then multiply those elements by 2 and add 10 to the rest.

# Expected Output (example):
[[12 14  6]
 [ 8 20 22]
 [10 24 16]]

In [20]:
import numpy as np 

ran_arr = np.random.randint(0, 10, size=9).reshape(3,3)
mask = ran_arr > 5

multi_op = ran_arr[mask] * 2
add_op = multi_op + 2

print(add_op)

[20 14 20]


Problem #4: Complex Element-wise Operations
Create arrays: a = [1, 2, 3, 4] and b = [10, 20, 30, 40]. Compute (a² + b) / (a + 1) element-wise.


# Expected Output:
[ 5.5   8.    9.75 11.2 ]

In [26]:
import numpy as np 

a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])

advance_op = ((a ** 2) + b) / (a + 1)

print(advance_op)

[ 5.5   8.    9.75 11.2 ]


Problem #5: Broadcasting with Different Dimensions
Create a 3x1 array: [[1], [2], [3]] and a 1x4 array: [[10, 20, 30, 40]]. Multiply them using broadcasting.

# Expected Output:
[[10 20 30 40]
 [20 40 60 80]
 [30 60 90 120]]

In [46]:
import numpy as np 

arr = np.array([[1], [2], [3]])
arr2 = np.array([[10, 20 ,30 , 40]])

multi_op = arr * arr2

print(multi_op)

[[ 10  20  30  40]
 [ 20  40  60  80]
 [ 30  60  90 120]]


Problem #6: Conditional Arithmetic with Where
Create an array: [-3, -1, 0, 2, 4, 6]. Use np.where() to replace negative numbers with 0 and keep positive numbers unchanged.

# Expected Output:
[0 0 0 2 4 6]

In [50]:
import numpy as np 

arr = np.array([-3, -1, 0, 2, 4, 6])

mask = np.where(arr < 0)
arr[mask] = 0 

print(arr)

[0 0 0 2 4 6]


Problem #7: Advanced Broadcasting with Strides
Create a 4x4 array of int32 and a 1x4 array of int32. Multiply them and verify they have the same strides in the second dimension.

# Expected Output:
4x4 array second dimension stride: 4
1x4 array second dimension stride: 4
Result second dimension stride: 4

In [55]:
import numpy as np 

arr = np.arange(16, dtype = np.int32).reshape(4,4)
arr2 = np.arange(4, dtype = np.int32).reshape(1,4)

multi_op = arr * arr2

first_dnm_4x4, sec_dnm_4x4 = arr.strides
first_dnm_1x4, sec_dnm_1x4 = arr2.strides
first_dnm_multi, sec_dnm_multi = multi_op.strides

print(f"""4x4 array second dimension stride: {sec_dnm_4x4}
1x4 array second dimension stride: {sec_dnm_1x4}
Result second dimension stride: {sec_dnm_multi}""")

4x4 array second dimension stride: 4
1x4 array second dimension stride: 4
Result second dimension stride: 4


Problem #8: Arithmetic with Fancy Indexing
Create a 5x5 array with values 0-24. Use fancy indexing to select elements at positions (0,0), (2,2), (4,4), then perform (selected * 3) - 5.

# Expected Output:
[-5 31 67]


In [65]:
import numpy as np 

arr = np.arange(0, 25).reshape(5,5)

row = [0,2,4]
column= [0,2,4]
fancy_index = arr[row, column]

adv_op = (fancy_index * 3) -5

print(adv_op)

[-5 31 67]


Problem #9: Multi-step Broadcasting Chain
Create arrays: a = [[1], [2]] (2x1), b = [[10, 20, 30]] (1x3), and c = [[100], [200], [300]] (3x1). Add them in sequence: first a + b, then result + c.

# Expected Output:
[[111 121 131]
 [212 222 232]]

In [70]:
import numpy as np 

arr = np.array([[1], [2]])
arr2 = np.array([[10, 20, 30]])
arr3 = np.array([[100], [200], [300]])

add_op = (arr + arr2) + np.transpose(arr3)

print(add_op)

[[111 221 331]
 [112 222 332]]


Problem #10: Division with Zero Handling
Create arrays: a = [10, 20, 0, 40] and b = [2, 0, 5, 8]. Use np.where() to handle division by zero by replacing with -1.

# Expected Output:
[ 5. -20.  0.  5.]

In [ ]:
import numpy as np

arr = np.array([10, 20, 0, 40])
arr2 = np.array([2, 0, 5, 8])

remove = np.where(arr2 == 0, -1, arr2)

div_op = arr / remove

print(div_op)

[  5. -20.   0.   5.]


Problem #11: Broadcasting Shape Compatibility
Create two arrays with shapes (3,3) and (2,2). Try to add them and catch the ValueError, then print the error message.

# Expected Output:
"operands could not be broadcast together with shapes (3,3) (2,2)"

In [89]:
import numpy as np 

arr = np.arange(3*3).reshape(3,3)
arr2 = np.arange(2*2).reshape(2,2)

try:
    add_op = arr + arr2
except ValueError as e:
    print(e)

operands could not be broadcast together with shapes (3,3) (2,2) 


Problem #12: Element-wise Power with Broadcasting
Create arrays: a = [[1, 2, 3], [4, 5, 6]] (2x3) and b = [1, 2, 3] (1x3). Raise each element of a to the power of the corresponding element in b.

# Expected Output:
[[  1   4  27]
 [  4  25 216]]

In [90]:
import numpy as np 

arr = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([1,2,3])

power_op = arr ** arr2

print(power_op)

[[  1   4  27]
 [  4  25 216]]


Problem #13: Arithmetic with Slice Assignment
Create a 4x4 array with values 1-16. Slice the center 2x2 block and multiply it by 10.

# Expected Output:
[[ 1  2  3  4]
 [ 5 60 70  8]
 [ 9 100 110 12]
 [13 14 15 16]]

In [97]:
import numpy as np

arr = np.arange(1, 17).reshape(4,4)
center_slices = arr[1:3, 1:3]
multi_scalar = center_slices * 10

arr[1:3, 1:3] = multi_scalar

print(arr)


[[  1   2   3   4]
 [  5  60  70   8]
 [  9 100 110  12]
 [ 13  14  15  16]]


Problem #14: Complex Number Arithmetic
Create arrays: a = [1+2j, 3+4j] and b = [2+1j, 1+3j]. Multiply them and print the result.

# Expected Output:
[0.+5.j -9.+13.j]

In [98]:
import numpy as np 

arr = np.array([1+2j, 3+4j])
arr2 = np.array([2+1j, 1+3j])

multi_op = arr * arr2

print(multi_op)

[ 0. +5.j -9.+13.j]


Problem #15: Broadcasting Memory Analysis
Create a 100x100 array and a 1x100 array. Compare their memory usage and the memory usage of their broadcasted product.

# Expected Output:
100x100 array: 80000 bytes
1x100 array: 800 bytes
Product: 80000 bytes (same as larger array)

In [101]:
import numpy as np

arr = np.zeros((100,100))
arr2 = np.zeros((1,100))
multi_op = arr * arr2

print(f"""100x100 array: {arr.nbytes} bytes
1x100 array: {arr2.nbytes} bytes
Product: {multi_op.nbytes} bytes (same as larger array)""")



100x100 array: 80000 bytes
1x100 array: 800 bytes
Product: 80000 bytes (same as larger array)


Problem #16: Conditional Operations with Multiple Arrays
Create arrays: a = [5, 10, 15, 20] and b = [8, 12, 15, 18]. Compute a * 2 where a > b, otherwise compute b / 2.

# Expected Output:
[ 4.  6. 30. 40.]

In [104]:
import numpy as np

arr = np.array([5, 10, 15, 20])
arr2 = np.array([8, 12, 15, 18])

adv_op = np.where(arr >= arr2, arr * 2, arr2 / 2)

print(adv_op)

[ 4.  6. 30. 40.]


Problem #17: Advanced Reshape with Broadcasting
Create a 1D array of 12 elements. Reshape to 3x4 and create a compatible 1D array [100, 200, 300, 400] for row-wise broadcasting, then add them.

# Expected Output:
[[100 201 302 403]
 [104 205 306 407]
 [108 209 310 411]]

In [109]:
import numpy as np 

arr = np.arange(12).reshape(3,4)

com_arr = np.array([100, 200, 300, 400])
add_op = arr + com_arr

print(add_op)

[[100 201 302 403]
 [104 205 306 407]
 [108 209 310 411]]


Problem #18: Arithmetic with NaN Handling
Create an array: [1, 2, np.nan, 4, 5]. Multiply by 2, then replace NaN values with 0.

# Expected Output:
[ 2.  4.  0.  8. 10.]

In [120]:
import numpy as np

arr = np.array([1, 2, np.nan, 4, 5])
multi_op = arr * 2
replace = np.where(np.isnan(arr), 0, arr)

print(replace)

[1. 2. 0. 4. 5.]


Problem #19: Multi-dimensional Power Operation
Create arrays: a = np.arange(8).reshape(2, 2, 2) and b = [[2, 3], [4, 5]]. Use broadcasting to raise each 2x2 slice of a to the power of b.

# Expected Output:
[[[   0     1]
  [  16   243]]
 [[  16   125]
  [1296 16807]]]

In [132]:
import numpy as np

arr = np.arange(8).reshape(2, 2, 2)
arr2 = np.array([[2, 3],
                 [4, 5]])

power_3d = arr ** arr2

print(power_3d)

[[[    0     1]
  [   16   243]]

 [[   16   125]
  [ 1296 16807]]]


Problem #20: Comprehensive Broadcasting Analysis
Create arrays: a with shape (3,1,4), b with shape (2,4), and c with shape (3,2,1). Add them together and analyze the broadcasting steps.

# Expected Output:
Step1: (3,1,4) + (2,4) -> (3,2,4)
Step2: (3,2,4) + (3,2,1) -> (3,2,4)
Final shape: (3, 2, 4)

In [134]:
import numpy as np

arr = np.zeros((3,1,4))
arr2 = np.zeros((2,4))
arr3 = np.zeros((3,2,1))

step_1 = arr + arr2
step_2 = step_1 + arr3 

print(f"""Step1: {arr.shape} + {arr2.shape} -> {step_1.shape}
Step2: {step_1.shape} + {arr3.shape} -> {step_2.shape}
Final shape: {step_2.shape}""")

Step1: (3, 1, 4) + (2, 4) -> (3, 2, 4)
Step2: (3, 2, 4) + (3, 2, 1) -> (3, 2, 4)
Final shape: (3, 2, 4)


END OF INTERMEDIATE LEVEL

Part 12 
Date: 11/27/25
Total Problem Solved: 20
Time Spent: 2 hr and 42 mins

Topic Include: Broadcasting and Arithmetic Operations (Add, Subtract, Multiply, Divide, etc.)

Difficulty: Intermediate(20)

START OF ADVANCE LEVEL

Problem #1: 3D Broadcasting with Specific Values
Create arrays: a = np.ones((2, 1, 3)) * [1, 2, 3] and b = np.ones((1, 4, 1)) * [1, 2, 3, 4]. Multiply them and analyze the resulting shape.

# Expected Output:
Result shape: (2, 4, 3)
First 2x2 slice:
[[[1. 2. 3.]
  [2. 4. 6.]]
 [[1. 2. 3.]
  [2. 4. 6.]]]

In [27]:
import numpy as np 

arr = np.ones((2, 1, 3)) * np.array([1, 2, 3])
arr2 = np.array([1, 2, 3, 4 ]).reshape(1,4,1)

multi_op = arr * arr2

first_2x2 = multi_op[:,:2, :]
print(f"Result shape: {multi_op.shape}")
print(f"""First 2x2 slice: 
{first_2x2}""")

Result shape: (2, 4, 3)
First 2x2 slice: 
[[[1. 2. 3.]
  [2. 4. 6.]]

 [[1. 2. 3.]
  [2. 4. 6.]]]


Problem #2: Broadcasting with Matrix Operations
Create a 3x2 array and a 2x1 array. Perform element-wise multiplication using broadcasting, then compare with matrix multiplication.

# Expected Output:
Element-wise result shape: (3, 2)
Matrix multiplication shape: (3, 1)

In [33]:
import numpy as np 

arr = np.arange(3*2).reshape(3,2)
arr2 = np.arange(2*1).reshape(2,1).reshape(1,2)
arr2_matrix = arr2.copy().reshape(2,1)

multi_op = arr * arr2
matrix_multi = arr @ arr2_matrix

print(f"Element-wise result shape: {multi_op.shape}")
print(f"Matrix multiplication shape: {matrix_multi.shape}")


Element-wise result shape: (3, 2)
Matrix multiplication shape: (3, 1)


Problem #3: Advanced Conditional Arithmetic
Create arrays: a = [[1, 2], [3, 4]] and b = [[5, 6], [7, 8]]. Compute (a + b) * (a - b) element-wise.

# Expected Output:
[[-24 -32]
 [-40 -48]]

In [34]:
import numpy as np 

arr = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

advance_op = (arr + arr2) * (arr - arr2)

print(advance_op)

[[-24 -32]
 [-40 -48]]


Problem #4: Broadcasting Memory Efficiency
Create a 100x100 array and a 1x100 array. Compare their memory usage and the memory usage of their broadcasted sum.

# Expected Output:
100x100 array: 80000 bytes
1x100 array: 800 bytes
Broadcasted sum: 80000 bytes


In [35]:
import numpy as np 

arr = np.zeros((100,100))
arr2 = np.zeros((1,100))

sums = arr + arr2

print(f"""100x100 array: {arr.nbytes} bytes
1x100 array: {arr2.nbytes} bytes
Broadcasted sum: {sums.nbytes} bytes""")

100x100 array: 80000 bytes
1x100 array: 800 bytes
Broadcasted sum: 80000 bytes


Problem #5: Complex Number Broadcasting
Create arrays: a = [[1+2j, 3+4j]] and b = [[1j], [2j]]. Multiply them and print the result.

# Expected Output:
[[-2.+1.j -4.+3.j]
 [-4.+2.j -8.+6.j]]

In [36]:
import numpy as np 

arr = np.array([[1+2j, 3+4j]])
arr2 = np.array([[1j], [2j]])

multi_op = arr * arr2

print(multi_op)

[[-2.+1.j -4.+3.j]
 [-4.+2.j -8.+6.j]]


Problem #6: Multi-operation Broadcasting
Create arrays: a = np.ones((3, 1, 2)), b = np.ones((1, 2, 2)), c = np.ones((3, 2, 1)). Compute (a * b) + c.

# Expected Output:
Shape: (3, 2, 2)
First slice:
[[[2. 2.]
  [2. 2.]]
 [[2. 2.]
  [2. 2.]]]

In [6]:
import numpy as np 

arr = np.ones((3, 1, 2))
arr2 = np.ones((1,2,2))
arr3 = np.ones((3,2,1))

adv_op = (arr * arr2) + arr3

print(f"Shape: {adv_op.shape}")
print(f"""First slice: 
{adv_op[:2]}""")

Shape: (3, 2, 2)
First slice: 
[[[2. 2.]
  [2. 2.]]

 [[2. 2.]
  [2. 2.]]]


Problem #7: Broadcasting with Fancy Indexing
Create a 4x4 array. Use fancy indexing to select rows [0, 2] and columns [1, 3], then broadcast addition with [100, 200].

# Expected Output:
[[101 203]
 [109 211]]


In [20]:
import numpy as np 

arr = np.arange(4*4).reshape(4,4)

rows = np.array([0, 2])
columns = np.array([1, 3])

fancy_index = np.ix_(rows, columns)

print(arr[fancy_index] + np.array([100, 200]))

[[101 203]
 [109 211]]


Problem #8: Memory Layout Impact
Create C-order and F-order arrays of shape 100x100. Compare their attributes and verify memory layout differences.

# Expected Output:
C-order: strides=(800, 8), C-contiguous=True
F-order: strides=(8, 800), F-contiguous=True

In [22]:
import numpy as np

arr_c = np.zeros((100, 100), order = 'C')
arr_f = np.zeros((100,100), order = 'F')

print(f"""C-order: strides={arr_c.strides}), C-contiguous= {arr_c.flags['C_CONTIGUOUS']}
F-order: strides={arr_f.strides}, F-contiguous={arr_f.flags['F_CONTIGUOUS']}""")

C-order: strides=(800, 8)), C-contiguous= True
F-order: strides=(8, 800), F-contiguous=True


Problem #9: Advanced Where with Conditions
Create array: [1, 5, 10, 15, 20]. Use np.where() to apply: values < 10 get squared, values >= 10 get doubled.

# Expected Output:
[ 1 25 20 30 40]

In [23]:
import numpy as np 

arr = np.array([1, 5, 10, 15, 20])

mask = np.where(arr < 10, arr ** 2, arr * 2)

print(mask)

[ 1 25 20 30 40]


Problem #10: Broadcasting with Reshape
Create arrays: a = np.arange(6).reshape(2, 3) and b = np.arange(3). Reshape b for column-wise broadcasting and multiply.

# Expected Output:
[[ 0  1  4]
 [ 0  4 10]]

In [24]:
import numpy as np 

arr = np.arange(6).reshape(2,3)
arr2 = np.arange(3).reshape(1,3) 

multi_op = arr * arr2 

print(multi_op)

[[ 0  1  4]
 [ 0  4 10]]


Problem #11: NaN Handling in Operations
Create array: [1, 2, np.nan, 4, 5]. Multiply by 2, then replace NaN values with -1.

# Expected Output:
[ 2.  4. -1.  8. 10.]

In [33]:
import numpy as np 

arr = np.array([1, 2, np.nan, 4, 5]) 
multi_scalar = arr * 2 

replace = np.where(np.isnan(multi_scalar), -1, multi_scalar)

print(replace)

[ 2.  4. -1.  8. 10.]


Problem #12: Data Type Promotion
Create arrays: a = np.array([1, 2], dtype=np.int32) and b = np.array([1.5, 2.5], dtype=np.float64). Multiply them and check the resulting data type.

# Expected Output:
[1.5 5. ]
float64

In [34]:
import numpy as np 

arr = np.array([1, 2], dtype = np.int32)
arr2 = np.array([1.5, 2.5], dtype = np.float64)

multi_op = arr * arr2 

print(multi_op)
print(multi_op.dtype)

[1.5 5. ]
float64


Problem #13: Advanced Slicing with Broadcasting
Create a 6x6 array. Use slicing to extract a checkerboard pattern, then broadcast multiplication with a 3x3 pattern.

# Expected Output:
[[ 0  0  0  0  0  0]
 [ 0  8  0 10  0 12]
 [ 0  0  0  0  0  0]
 [ 0 20  0 22  0 24]
 [ 0  0  0  0  0  0]
 [ 0 32  0 34  0 36]]

In [45]:
import numpy as np
arr = np.arange(6*6).reshape(6,6) 
checkerboard = np.zeros((6,6), dtype = np.int32)

rows = slice(1, None, 2)
cols = slice(1, None, 2)

block = arr[rows, cols]

checkerboard[rows, cols] = block + 1
print(checkerboard)


[[ 0  0  0  0  0  0]
 [ 0  8  0 10  0 12]
 [ 0  0  0  0  0  0]
 [ 0 20  0 22  0 24]
 [ 0  0  0  0  0  0]
 [ 0 32  0 34  0 36]]


Problem #14: Broadcasting Rules Verification
Test broadcasting with arrays: shape (3,1) with (1,4), and shape (2,1,3) with (4,2,1). Print success/failure for each.

# Expected Output:
(3,1) with (1,4): Success - shape (3,4)
(2,1,3) with (4,2,1): Success - shape (4,2,3)


In [53]:
import numpy as np 

arr = np.zeros((3,1))
arr2 = np.zeros((1,4))

arr3 = np.zeros((2,1,3))
arr4 = np.zeros((4,2,1))

print(f"{arr.shape} with {arr2.shape}: Success - shape {(arr + arr2).shape}")

try:
    (arr3 + arr4).shape
except ValueError as e:
    print(f"{arr3.shape} with {arr4.shape}: Failure - {e}")

(3, 1) with (1, 4): Success - shape (3, 4)
(2, 1, 3) with (4, 2, 1): Failure - operands could not be broadcast together with shapes (2,1,3) (4,2,1) 


Problem #15: In-place vs Regular Operations
Create an array and demonstrate the difference between in-place and regular broadcasting operations.

# Expected Output:
Regular operation: new array created
In-place operation: original array modified
Memory addresses differ for regular, same for in-place

In [60]:
import numpy as np

a = np.array([1, 2, 3], dtype=int)
b = np.array([10, 20, 30], dtype=int)

print("Before any op")
print("a =", a)
print("a id =", id(a))
print("a data ptr = ", a.ctypes.data)
print()

c = a + b   
print("Regular operation: c = a + b")
print("a after regular op:", a)           
print("c = ", c)
print("a id = ", id(a))
print("c id = ", id(c))                      
print("a data ptr = ", a.ctypes.data)
print("c data ptr = ", c.ctypes.data)      
print()

d = np.array([1, 2, 3], dtype=int)         
ptr_before = d.ctypes.data
print("Before in-place: d id = ", id(d), "data ptr:", ptr_before)

d += b    
ptr_after = d.ctypes.data
print("In-place operation =  d += b")
print("d after in-place = ", d)
print("d id after in-place = ", id(d))       
print("data ptr equal = ", ptr_before == ptr_after)  
print("d data ptr = ", ptr_after)


Before any op
a = [1 2 3]
a id = 2219997954864
a data ptr =  2219701514576

Regular operation: c = a + b
a after regular op: [1 2 3]
c =  [11 22 33]
a id =  2219997954864
c id =  2219997955536
a data ptr =  2219701514576
c data ptr =  2219701516848

Before in-place: d id =  2219997954096 data ptr: 2219701515760
In-place operation =  d += b
d after in-place =  [11 22 33]
d id after in-place =  2219997954096
data ptr equal =  True
d data ptr =  2219701515760


Problem #16: Mathematical Functions with Broadcasting
Create arrays: a = [[0, np.pi/2], [np.pi, 3*np.pi/2]] and b = [1, 2]. Compute np.sin(a) * b.

# Expected Output:
[[ 0.   2. ]
 [ 0.  -2. ]]

In [64]:
import numpy as np 

arr = np.array([[0, np.pi/2], [np.pi, 3*np.pi/2]])
arr2 = np.array([1, 2]) 

math_op = np.sin(arr) * arr2 

print(np.round(math_op, 1))

[[ 0.  2.]
 [ 0. -2.]]


Problem #17: Conditional Broadcasting
Create arrays: a = [[1, 2], [3, 4]] and b = [[5, 6]]. Compute a * 2 where a > b, else compute b * 3.

# Expected Output:
[[15 18]
 [15 18]]

In [ ]:
import numpy as np 

arr = np.array([[1, 2],
                [3, 4]])
arr2 = np.array([[5,6]])

adv_op = np.where(arr > arr2, arr * 2, arr2 * 3)

print(adv_op)

[[15 18]
 [15 18]]


Problem #18: Complex Conjugation with Broadcasting
Create complex arrays and demonstrate conjugation with broadcasting across dimensions.

# Expected Output:
Original: [[1.+2.j 3.+4.j]]
Conjugated: [[1.-2.j 3.-4.j]]
After broadcasting: [[1.-2.j 3.-4.j]
 [1.-2.j 3.-4.j]]

In [71]:
import numpy as np 

com_arr = np.array([[1.+2.j ,3.+4.j]])

conju_arr = np.conjugate(com_arr)

repeat = np.tile(conju_arr, (2,1))

print(f"""Original: {com_arr}
Conjugated: {conju_arr}
After broadcasting: {repeat}""")

Original: [[1.+2.j 3.+4.j]]
Conjugated: [[1.-2.j 3.-4.j]]
After broadcasting: [[1.-2.j 3.-4.j]
 [1.-2.j 3.-4.j]]


Problem #19: Power Operations with Broadcasting
Create arrays: a = [[1, 2], [3, 4]] and b = [2, 3]. Compute a ** b using broadcasting.

# Expected Output:
[[ 1  8]
 [ 9 64]]

In [72]:
import numpy as np 

arr = np.array([[1, 2],
                [3, 4]])
arr2 = np.array([2, 3])

power_op = arr ** arr2

print(power_op)

[[ 1  8]
 [ 9 64]]


Problem #20: Comprehensive Workflow
Create arrays, perform: reshape → broadcast → arithmetic → indexing. Track all attribute changes.

# Expected Output:
Step 1: Created (6,) -> reshaped to (2,3)
Step 2: Broadcast with (3,) -> (2,3)
Step 3: (array * 2) + 10
Step 4: Indexed result shape: (2, 2)
Final: [[10 14]
 [16 20]]

In [80]:
import numpy as np 

arr = np.arange(6)
arr2 = np.arange(3)
arr_reshape = arr.copy().reshape(2,3)
arr_broadcast = arr_reshape + arr2

arr_arithmetic = (arr_broadcast * 2) + 10
arr_index = arr_arithmetic[0:2, 0: 2]

print(f"""Step 1: Created {arr.shape} -> reshape to {arr_reshape.shape}
Step 2: Broadcast with {arr2.shape} -> {arr_broadcast.shape}
Step 3: (arr * 2) + 10 = {arr_arithmetic}
Step 4: Indexed result shape: {arr_index.shape}
Final: {arr_index}""")

Step 1: Created (6,) -> reshape to (2, 3)
Step 2: Broadcast with (3,) -> (2, 3)
Step 3: (arr * 2) + 10 = [[10 14 18]
 [16 20 24]]
Step 4: Indexed result shape: (2, 2)
Final: [[10 14]
 [16 20]]


Part 13 
Date: 11/29/25
Total Problem Solved: 20
Time Spent: 2 hr and 39 mins

Topic Include: Broadcasting and Arithmetic Operations (Add, Subtract, Multiply, Divide, etc.)

Difficulty: Advance(20)