Problem #1: The Fundamental Array

Create a 1-dimensional NumPy array from the Python list [1, 2, 3, 4, 5] and print it.

Expected Output:

[1 2 3 4 5]

Solution Below:

In [ ]:
import numpy as np 

a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


Problem #2: A Line of Zeroes

Create a 1D array of length 10 where every element is 0 and print it.

Expected Output:

[0 0 0 0 0 0 0 0 0 0]

Solution Below