# DOUBLE CLICK THE PROBLEM CELL TO SEE THE CORRECT FORMAT OF THE PROBLEM AND EXPECTED OUTPUT

# START OF MODULE 4 - BROADCASTING AND ARITHMETIC OPERATIONS

BEGINNER LEVEL

Problem #1: Basic Array Addition
Create two 1D arrays: a = [1, 2, 3] and b = [4, 5, 6]. Add them together and print the result.

# Expected Output:
[5 7 9]

In [2]:
import numpy as np 

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = a + b 

print(c)

[5 7 9]


Problem #2: Scalar Broadcasting - Addition
Create a 1D array: [10, 20, 30, 40]. Add the scalar value 5 to every element and print the result.

# Expected Output:
[15 25 35 45]

In [3]:
import numpy as np 

arr = np.array([10, 20, 30, 40])

scalar_add = arr + 5 

print(scalar_add)

[15 25 35 45]


Problem #3: Array Subtraction
Create two 2x2 arrays: [[5, 6], [7, 8]] and [[1, 2], [3, 4]]. Subtract the second array from the first and print the result.

# Expected Output:
[[4 4]
 [4 4]]

In [7]:
import numpy as np 

arr1 = np.array([[5, 6],
                 [7, 8]])
arr2 = np.array([[1, 2],
                 [3, 4]])

sub = arr1 - arr2

print(sub)

[[4 4]
 [4 4]]


Problem #4: Scalar Multiplication
Create a 1D array: [2, 4, 6, 8]. Multiply every element by 3 and print the result.

# Expected Output:
[ 6 12 18 24]

In [9]:
import numpy as np 

arr = np.arange(2,9,2)

scalar_multi = arr * 3

print(scalar_multi)

[ 6 12 18 24]


Problem #5: Element-wise Multiplication
Create two 3-element arrays: [1, 2, 3] and [4, 5, 6]. Multiply them element-wise and print the result.

# Expected Output:
[ 4 10 18]


In [10]:
import numpy as np 

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

one_dimn_multi = arr1 * arr2

print(one_dimn_multi)

[ 4 10 18]


Problem #6: Array Division
Create two arrays: [10, 20, 30] and [2, 4, 5]. Divide the first array by the second element-wise and print the result.

# Expected Output:
[5. 5. 6.]

In [11]:
import numpy as np 

arr1 = np.array([10, 20, 30])
arr2 = np.array([2, 4, 5])

div_op = arr1 / arr2 

print(div_op)

[5. 5. 6.]


Problem #7: Broadcasting with Different Shapes
Create a 2D array: [[1, 2, 3], [4, 5, 6]] and a 1D array: [10, 20, 30]. Add them using broadcasting and print the result.

# Expected Output:
[[11 22 33]
 [14 25 36]]

In [15]:
import numpy as np 

arr1 =  np.array([[1, 2, 3],
                  [4, 5, 6]])

arr2 = np.array([10, 20, 30])

add_op = arr1 + arr2

print(add_op)

[[11 22 33]
 [14 25 36]]


Problem #8: Scalar Division
Create a 2x2 array: [[10, 20], [30, 40]]. Divide every element by 10 and print the result.

# Expected Output:
[[1. 2.]
 [3. 4.]]

In [16]:
import numpy as np 

arr = np.array([[10, 20], [30, 40]])

scalar_div = arr / 10 

print(scalar_div)

[[1. 2.]
 [3. 4.]]


Problem #9: Mixed Operations
Create an array: [1, 2, 3, 4]. Perform the operation: (array * 2) + 5 and print the result.

# Expected Output:
[ 7  9 11 13]


In [18]:
import numpy as np 

arr = np.array([1,2,3,4])

scalar_multi = (arr * 2) + 5
print(scalar_multi)

[ 7  9 11 13]


Problem #10: Broadcasting Row Vector
Create a 3x1 array: [[1], [2], [3]] and a 1x3 array: [[10, 20, 30]]. Add them using broadcasting and print the result.

# Expected Output:
[[11 21 31]
 [12 22 32]
 [13 23 33]]

In [20]:
import numpy as np 

arr_3_1 = np.array([[1], [2], [3]])
arr_1_3 = np.array([[10,20,30]])

print(arr_3_1 + arr_1_3)

[[11 21 31]
 [12 22 32]
 [13 23 33]]


Problem #11: Arithmetic with Array Attributes
Create a 2x3 array and a 1x3 array. Add them, then print the shape of the result.

# Expected Output:
(2, 3)

In [23]:
import numpy as np 

arr1 = np.arange(2*3).reshape(2,3)
arr2 = np.arange(1*3).reshape(1,3)

arr3 = arr1 + arr2 

print(arr3.shape)

(2, 3)


Problem #12: Division with Different Data Types
Create an integer array: [10, 20, 30] and divide by integer 3. Print the result and its data type.

# Expected Output:
[3.33333333 6.66666667 10.        ]
float64

In [24]:
import numpy as np 

int_arr = np.array([10, 20, 30])
scalar_div = int_arr / 3

print(scalar_div)
print(scalar_div.dtype)

[ 3.33333333  6.66666667 10.        ]
float64


Problem #13: Broadcasting with Reshape
Create a 1D array of 6 elements and reshape to 2x3. Create another 1D array of 3 elements. Multiply them using broadcasting and print the result.

# Expected Output:
[[ 0  1  4]
 [ 9 16 25]]

In [27]:
import numpy as np 

arr = np.arange(6).reshape(2,3)
arr2 = np.arange(3)

multi_op = arr * arr2 

print(multi_op)

[[ 0  1  4]
 [ 0  4 10]]


Problem #14: Compound Arithmetic Operations
Create arrays: a = [2, 4, 6] and b = [1, 2, 3]. Calculate (a + b) * (a - b) and print the result.

# Expected Output:
[ 3 12 27]


In [28]:
import numpy as np 

a = np.array([2, 4, 6])
b = np.array([1, 2, 3])

func_op = (a + b) * (a - b)

print(func_op)

[ 3 12 27]


Problem #15: Broadcasting with Slicing
Create a 4x4 array with values 1-16. Slice to get the first 2 rows, then add a 1D array [100, 200] using broadcasting (properly aligned).

# Expected Output:
[[101 102 103 104]
 [205 206 207 208]]

In [39]:
import numpy as np 

arr = np.arange(1, 4*4 + 1).reshape(4,4)
arr2 = np.array([100, 200]).reshape(2,1)
slices = arr[:2]

print(slices + arr2)


[[101 102 103 104]
 [205 206 207 208]]


Problem #16: Element-wise Power Operation
Create an array: [2, 3, 4]. Raise each element to the power of 3 and print the result.

# Expected Output:
[ 8 27 64]

In [40]:
import numpy as np 

arr = np.array([2, 3, 4 ])

scalar_power = arr ** 3 

print(scalar_power)

[ 8 27 64]


Problem #17: Broadcasting with Transpose
Create a 3x1 array and a 1x3 array. Multiply them after transposing one to make broadcasting work correctly.

# Expected Output:
[[ 0  0  0]
 [ 0  1  2]
 [ 0  2  4]]

In [ ]:
import numpy as np 

arr1 = np.arange(3*1).reshape(3,1)
arr2 = np.arange(1*3).reshape(1,3)

#TRANSPOSE arr1 
trans_arr1 = np.transpose(arr1)
trans_arr2 = np.transpose(arr2)
multi_op = trans_arr1 * trans_arr2

print(multi_op)


[[0 0 0]
 [0 1 2]
 [0 2 4]]


Problem #18: Arithmetic with Boolean Indexing
Create an array: [5, 10, 15, 20, 25]. Use boolean indexing to select elements greater than 10, then multiply the selected elements by 2.

# Expected Output:
[30 40 50]

In [49]:
import numpy as np 

arr = np.arange(5, 26, 5)
bool_mask = arr > 10 

multi_op = arr[bool_mask] * 2

print(multi_op)

[30 40 50]


Problem #19: Mixed Data Type Operations
Create an integer array: [1, 2, 3] and a float array: [1.5, 2.5, 3.5]. Multiply them and check the resulting data type.

# Expected Output:
[ 1.5  5.  10.5]
float64


In [50]:
import numpy as np 

int_arr = np.array([1, 2, 3])
float_arr = np.array([1.5, 2.5, 3.5])

multi_op = int_arr * float_arr

print(multi_op)
print(multi_op.dtype)

[ 1.5  5.  10.5]
float64


Problem #20: Comprehensive Broadcasting Example
Create a 2x3 array and a 3-element 1D array. Perform addition, multiplication, and division operations between them using broadcasting and print all results.

# Expected Output:
Addition:
[[ 1  3  5]
 [ 4  6  8]]
Multiplication:
[[ 0  2  6]
 [ 0  5 12]]
Division:
[[0.  2.  1.5]
 [0.  5.  3. ]]

In [71]:
import numpy as np 

arr = np.arange(1, 2 * 3 + 1).reshape(2,3)
arr2 = np.arange(3)

add_op = arr + arr2 
multi_op = arr * arr2 

mask = arr2 > 0

div_op = np.divide(arr, arr2, where = mask)


print("Addtion:")
print(add_op)
print("Multiplication:")
print(multi_op)
print("Division:")
print(div_op)


Addtion:
[[1 3 5]
 [4 6 8]]
Multiplication:
[[ 0  2  6]
 [ 0  5 12]]
Division:
[[0.  2.  1.5]
 [0.  5.  3. ]]


Part 11 
Date: 11/24/25
Total Problem Solved: 20
Time Spent: 2 hr and 30 mins

Topic Include: Broadcasting and Arithmetic Operations (Add, Subtract, Multiply, Divide, etc.)

Difficulty: Beginner(20)