Problem #1: The Fundamental Array

Create a 1-dimensional NumPy array from the Python list [1, 2, 3, 4, 5] and print it.

Expected Output:

[1 2 3 4 5]

Solution Below:

In [ ]:
import numpy as np 

a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


Problem #2: A Line of Zeroes

Create a 1D array of length 10 where every element is 0 and print it.

Expected Output:

[0 0 0 0 0 0 0 0 0 0]

Solution Below

In [3]:
import numpy as np

a = np.full(10,0)
print(a)

[0 0 0 0 0 0 0 0 0 0]


Problem #3: The Identity Matrix

Create a 3x3 identity matrix (2D array) and print it.

Expected Output:

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

 Solution Below:

In [9]:
import numpy as np

a = np.array([[1.,0.,0.],[0.,1.,0.],[0.,0.,1.]])
print(a)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Problem #4: A Range of Numbers

Create a 1D array containing the numbers from 10 to 25 (inclusive) and print it.

Expected Output:

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25]

Solution Below:

In [10]:
import numpy as np

array = np.arange(10,26)
print(array)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25]


Problem #5: Check the Type

Create a 1D array from the list [1.5, 2.5, 3.5]. Print the array and then print its data type (dtype).

Expected Output:

[1.5 2.5 3.5]
float64

Solution Below:

In [11]:
import numpy as np

array = np.array([1.5, 2.5, 3.5])
print(array)
print(array.dtype)

[1.5 2.5 3.5]
float64


Problem #6: Forcing a Type

Create a 1D array from the list [1, 2, 3, 4] but explicitly set the data type to float32. Print the array and its dtype.

Expected Output:

[1. 2. 3. 4.]
float32

Solution Below:

In [16]:
import numpy as np

array = np.array([1,2,3,4], dtype = np.float32)

print(array)
print(array.dtype)


[1. 2. 3. 4.]
float32


Problem #7: A Square of Sequential Integers

Create a 1D array with elements from 1 to 9, then reshape it into a 3x3 matrix. Print the new 2D array.

Expected Output:

[[1 2 3]
 [4 5 6]
 [7 8 9]]

Solution Below:

In [17]:
import numpy as np

array = np.arange(1,10).reshape(3,3)

print(array)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


Problem #8: The Transpose
Create a 2x4 array from a range of 8 numbers, reshape it, and then print its transpose.

Expected Output (Original 2x4):

[[0 1 2 3]
 [4 5 6 7]]

Expected Output (Transpose):

[[0 4]
 [1 5]
 [2 6]
 [3 7]]

Solution Below:

In [21]:
import numpy as np 

array = np.arange(8).reshape(2,4)

transposed_array =  np.transpose(array)

print(array, "\n")
print(transposed_array)

[[0 1 2 3]
 [4 5 6 7]] 

[[0 4]
 [1 5]
 [2 6]
 [3 7]]


Problem #9: Flatten it Out

Create a 2x3 array and then flatten it (convert it to a 1D array). Print both the original and the flattened array.

Expected Output (Original):

[[10 20 30]
 [40 50 60]]

Expected Output (Flattened):

[10 20 30 40 50 60]

Solution Below:

In [26]:
import numpy as np 

array = np.arange(10,61,10).reshape(2,3)
print(array,"\n")

flatten_array = array.flatten()
print(flatten_array)

[[10 20 30]
 [40 50 60]] 

[10 20 30 40 50 60]


Problem #10: A Diagonal Line

Create a 1D array with [5, 6, 7, 8] and then convert it into a 2D array with 4 rows and 1 column. Print the result.

Expected Output:

[[5]
 [6]
 [7]
 [8]]

Solution Below:

In [27]:
import numpy as np 

array = np.array([5,6,7,8]).reshape(4,1)
print(array)

[[5]
 [6]
 [7]
 [8]]


Problem #11: Stacking Vertically

Create two 1D arrays: a = [1, 2, 3] and b = [4, 5, 6]. Stack them vertically to form a 2x3 array and print it.

Expected Output:

[[1 2 3]
 [4 5 6]]

Solution Below:

In [28]:
import numpy as np

array_1 = np.array([1 ,2, 3])
array_2 = np.array([4, 5, 6])

array_3 = np.concatenate((array_1, array_2)).reshape(2,3)
print(array_3)

[[1 2 3]
 [4 5 6]]


Problem #12: Stacking Horizontally

Using the same arrays a and b from the previous problem, stack them horizontally to form a 1x6 array and print it.

Expected Output:

[1 2 3 4 5 6]

Solution Below:

In [ ]:
import numpy as np

array_1 = np.array([1, 2, 3])
array_2 = np.array([4, 5, 6])
array_3 = np.concatenate((array_1, array_2))

print(array_3)

[1 2 3 4 5 6]


Problem #13: A Constant Matrix

Create a 2x5 array filled entirely with the number 7 and print it.

Expected Output:

[[7 7 7 7 7]
 [7 7 7 7 7]]

Solution Below:

In [ ]:
import numpy as np

seven_array = np.full((2,5),7)
print(seven_array)

[[7 7 7 7 7]
 [7 7 7 7 7]]


Problem #14: Evenly Spaced Intervals

Create a 1D array of 5 evenly spaced numbers between 0 and 1 (inclusive) and print it.

Expected Output:

[0.   0.25 0.5  0.75 1.  ]

Solution Below:

In [ ]:
import numpy as np

linspace = np.linspace(0,1,num = 5)
print(linspace)

[0.   0.25 0.5  0.75 1.  ]


Problem #15: The Shape of Things
Create a 2D array with 2 rows and 4 columns from a range of 8 numbers. Print the array and then print its shape.

Expected Output (Array):

[[0 1 2 3]
 [4 5 6 7]]

Expected Output (Shape):

(2, 4)

Solution Below:

In [43]:
import numpy as np

array = np.arange(8).reshape(2,4)

print(array,"\n")
print(array.shape)

[[0 1 2 3]
 [4 5 6 7]] 

(2, 4)


Part 1 
Date: 10/27/25
Total Problem Solved: 15
Time Spent: 1 hr and 2 mins

Topic Include: ndarray object, Data Types (dtype), Array Creation Routines, Array Manipulation.
Difficulty: Beginner

Problem #16: Changing Dimensions

Create a 1D array of 12 elements. Reshape it into a 3x4 array and print it.

Expected Output:

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Solution Below:

In [3]:
import numpy as np

array = np.arange(12).reshape(3,4)


print(array)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


Problem #17: A Matrix of Randomness

Create a 2x3 array with random values (using np.random.rand). Print the array. (Note: Your output values will vary).

Example Output (your values will be different):

[[0.12345678 0.45678901 0.78901234]
 [0.34567891 0.67890123 0.90123456]]

Solution Below:

In [4]:
import numpy as np

ran_array = np.random.rand(2,3)

print(ran_array)

[[0.62441034 0.07968286 0.48043626]
 [0.46777431 0.90741323 0.86054998]]


Problem #18: 

Create two 1D arrays, x = [1, 2] and y = [3, 4]. Concatenate them into a single 1D array and print the result.

Expected Output:

[1 2 3 4]

Solution Below:

In [5]:
import numpy as np

x = np.array([1,2])
y = np.array([3,4])

conca = np.concatenate((x,y))

print(conca)

[1 2 3 4]


Problem #19: The Number of Dimensions
Create a 3D array with shape (2, 2, 3) filled with zeros. Print the array and then print the number of dimensions (ndim).


Expected Output (Array):

[[[0. 0. 0.]
  [0. 0. 0.]]
 [[0. 0. 0.]
  [0. 0. 0.]]]

Expected Output (ndim):

3

Solution Below:

In [11]:
import numpy as np

zero_3dim = np.full((2, 2, 3),0.)

print(zero_3dim, "\n")
print(zero_3dim.ndim)


[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]] 

3


Problem #20: Complex Numbers
Create a 1D array of complex numbers where the real part is [1, 2] and the imaginary part is [3, 4]. 
Print the array and its dtype.

Expected Output:

[1.+3.j 2.+4.j]
complex128

Solution Below:

In [15]:
import numpy as np 

real = np.array([1, 2])
imagi = np.array([3, 4])

complex_array = real + 1j * imagi

print(complex_array)

[1.+3.j 2.+4.j]


ARRAY AND CREATION 

Intermediate Level

20 PROBLEMS

Problem #1: Structured Sequence with Step

Create a 1D array of even numbers from 2 to 20 (inclusive) and print it.

Expected Output:

[ 2  4  6  8 10 12 14 16 18 20]

SOLUTION BELOW:

In [16]:
import numpy as np

even_array = np.arange(2, 21, 2)

print(even_array)

[ 2  4  6  8 10 12 14 16 18 20]


Problem #2: Multi-dimensional Zeros with Specific Type

Create a 4x3 array of zeros with data type int16 and print both the array and its dtype.

Expected Output:

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
int16

SOLUTION BELOW:

In [18]:
import numpy as np

zeros_int16 = np.full((4,3),0, dtype = np.int16)

print(zeros_int16)
print(zeros_int16.dtype)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
int16


Problem #3: Complex Reshaping Challenge
Create a 1D array with numbers from 1 to 24, then reshape it into a 3D array with dimensions 2x3x4. Print the shape and the entire array.

# Expected Output (Shape):

(2, 3, 4)
# Expected Output (First 2D slice):

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]
 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]

SOLUTION BELOW:

In [20]:
import numpy as np

array_3d = np.arange(1,25).reshape(2,3,4)

print(array_3d.shape, "\n")
print(array_3d)

(2, 3, 4) 

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


Problem #4: Boolean Data Type Conversion

Create an array from the list [0, 1, 0, 1, 1, 0] and convert it to boolean dtype. Print the result.


# Expected Output:

[False  True False  True  True False]

SOLUTION BELOW:

In [ ]:
import numpy as np

boolss = np.array([0, 1, 0, 1, 1, 0], dtype = np.bool)

print(boolss)

[False  True False  True  True False]


Problem #5: Advanced Stacking

Create three 1D arrays: a = [1, 2], b = [3, 4], c = [5, 6]. Stack them to create a 3x2 array and print it.


# Expected Output:
[[1 2]
 [3 4]
 [5 6]]

SOLUTION BELOW:

In [27]:
import numpy as np

a = [1, 2]
b = [3, 4]
c = [5, 6]

three_by_two = np.concatenate((a,b,c)).reshape(3,2)
print(three_by_two)

[[1 2]
 [3 4]
 [5 6]]


Problem #6: Multi-axis Concatenation
Create two 2x3 arrays filled with 1s and 2s respectively. Concatenate them along axis 0, then along axis 1. 
Print both results.


# Expected Output (axis=0):
[[1. 1. 1.]
 [1. 1. 1.]
 [2. 2. 2.]
 [2. 2. 2.]]
 
# Expected Output (axis=1):
[[1. 1. 1. 2. 2. 2.]
 [1. 1. 1. 2. 2. 2.]]

In [31]:
import numpy as np

ones = np.full((2,3),1.)
twos = np.full((2,3),2.)

axis_0 = np.concatenate((ones,twos), axis = 0)
axis_1 = np.concatenate((ones,twos), axis = 1)

print(axis_0, "\n")
print(axis_1)

[[1. 1. 1.]
 [1. 1. 1.]
 [2. 2. 2.]
 [2. 2. 2.]] 

[[1. 1. 1. 2. 2. 2.]
 [1. 1. 1. 2. 2. 2.]]


Problem #7: Flattening Order Matters
Create a 2x3 array [[1, 2, 3], [4, 5, 6]]. 
Flatten it using both 'C' (row-major) and 'F' (column-major) orders and print both.

# Expected Output (C-order):

[1 2 3 4 5 6]
# Expected Output (F-order):

[1 4 2 5 3 6]

In [33]:
import numpy as np

array_1 = np.array([[1, 2, 3], [4, 5, 6]])

c_flat = array_1.flatten(order = 'C')
f_flat = array_1.flatten(order = 'F')

print(c_flat)
print(f_flat)

[1 2 3 4 5 6]
[1 4 2 5 3 6]


Problem #8: Advanced Transpose with Reshape
Create a 1D array of 12 elements, reshape to 3x4, then transpose to 4x3. Print the original shape and final shape.

# Expected Output (Original Shape):

(3, 4)
# Expected Output (Final Shape):

(4, 3)

In [36]:
import numpy as np

array_1 = np.arange(1,13).reshape(3,4)
transpose_array_1 = np.transpose(array_1)

print(array_1.shape)
print(transpose_array_1.shape)


(3, 4)
(4, 3)


Problem #9: Creating Arrays from Ranges with Specific Data Type
Create an array from 0 to 10 (exclusive) with step 2, but with data type complex64. Print the array and dtype.


# Expected Output:

[0.+0.j 2.+0.j 4.+0.j 6.+0.j 8.+0.j]
complex64

In [37]:
import numpy as np

com_array = np.arange(0,11,2,dtype = np.complex64)
print(com_array)
print(com_array.dtype)

[ 0.+0.j  2.+0.j  4.+0.j  6.+0.j  8.+0.j 10.+0.j]
complex64


Problem #10: Multi-dimensional Identity
Create a 4x4 identity matrix with uint8 data type. Print the array and verify the dtype.


# Expected Output:
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
uint8

In [42]:
import numpy as np

identity = np.identity(4, dtype = np.uint8)
print(identity)
print(identity.dtype)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
uint8


Part 2 
Date: 10/29/25
Total Problem Solved: 15
Time Spent: 1 hr and 10 mins

Topic Include: ndarray object, Data Types (dtype), Array Creation Routines, Array Manipulation.

Difficulty: Beginner(5) and Intermediate(10)