# DOUBLE CLICK THE PROBLEM CELL TO SEE THE CORRECT FORMAT OF THE PROBLEM AND EXPECTED OUTPUT

Start of Idenxing and Slicing Module

Problem #1: Basic 1D Indexing
Create a 1D array with values [10, 20, 30, 40, 50]. Access and print the third element (index 2).

# Expected Output:

30

In [2]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
print(arr[2])

30


Problem #2: Negative Indexing
Using the same array from Problem #1, access and print the last element using negative indexing.

# Expected Output:

50


In [3]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50])
print(arr1[-1])

50


Problem #3: Basic 1D Slicing
Create a 1D array with values [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]. Slice and print elements from index 3 to 7 
(inclusive of 3, exclusive of 7).

# Expected Output:

[3 4 5 6]

In [4]:
import numpy as np

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

slices = arr[3:7]
print(slices)

[3 4 5 6]


Problem #4: Slicing with Steps
Using the same array from Problem #3, slice and print every second element from the entire array.

# Expected Output:

[0 2 4 6 8]

In [5]:
import numpy as np

arr1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

second_elem = arr1[::2]

print(second_elem)

[0 2 4 6 8]


Problem #5: Reverse Array with Slicing
Using the same array from Problem #3, slice and print the array in reverse order.

# Expected Output:

[9 8 7 6 5 4 3 2 1 0]

In [7]:
import numpy as np

arr2 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

reverse_arr2 = arr2[::-1]
print(reverse_arr2)

[9 8 7 6 5 4 3 2 1 0]


Problem #6: 2D Array Indexing
Create a 2D array: [[1, 2, 3], [4, 5, 6], [7, 8, 9]]. Access and print the element at row 1, column 2.

# Expected Output:

6

In [8]:
import numpy as np

arr_2d = np.array([[1, 2, 3], 
                   [4, 5, 6], 
                   [7, 8, 9]])

print(arr_2d[1,2])

6


Problem #7: 2D Array Slicing
Using the same array from Problem #6, slice and print the first two rows and all columns.

# Expected Output:

[[1 2 3]
 [4 5 6]]

In [11]:
import numpy as np

arr_2 = np.array([[1, 2, 3], 
                   [4, 5, 6], 
                   [7, 8, 9]])

two_r_all_colms = arr_2[:2,:]

print(two_r_all_colms)

[[1 2 3]
 [4 5 6]]


Problem #8: Column Slicing
Using the same array from Problem #6, slice and print the second column (index 1) from all rows.

# Expected Output:

[2 5 8]

In [13]:
import numpy as np

arr_22 = np.array([[1, 2, 3], 
                   [4, 5, 6], 
                   [7, 8, 9]])

sec_colms_all_rows = arr_22[:,1]
print(sec_colms_all_rows)

[2 5 8]


Problem #9: Submatrix Extraction
Create a 4x4 array with values 0 to 15: [[0,1,2,3], [4,5,6,7], [8,9,10,11], [12,13,14,15]]. 
Extract and print the center 2x2 submatrix.

# Expected Output:

[[5 6]
 [9 10]]

In [17]:
import numpy as np

arr = np.arange(16).reshape(4,4)

center_submatrix = arr[1:3,1:3]
print(center_submatrix)

[[ 5  6]
 [ 9 10]]


Problem #10: Slicing with Start/End/Step
Create a 1D array from 0 to 19. Extract and print elements from index 5 to 15 with step 3.

# Expected Output:

[ 5  8 11 14]

In [19]:
import numpy as np

arr = np.arange(20)

slices = arr[5: 16: 3]
print(slices)

[ 5  8 11 14]


Problem #11: Integer Array Indexing (Fancy Indexing)
Create a 1D array: [100, 200, 300, 400, 500]. Use integer array indexing to extract elements at indices [0, 2, 4] and 
print them.

# Expected Output:

[100 300 500]

In [20]:
import numpy as np

arr = np.array([100, 200, 300, 400, 500])
indices = [0, 2, 4]

int_index = arr[indices]

print(int_index)

[100 300 500]


Problem #12: 2D Fancy Indexing
Create a 2D array: [[1, 2], [3, 4], [5, 6], [7, 8]]. Use fancy indexing to extract rows at indices [0, 2, 3] and
 print the result.

# Expected Output:

[[1 2]
 [5 6]
 [7 8]]

In [22]:
import numpy as np

arr_2d = np.arange(1,9).reshape(4,2)
indices = [0, 2, 3]

int_indx = arr_2d[indices]

print(int_indx)

[[1 2]
 [5 6]
 [7 8]]


Problem #13: Boolean Indexing - Basic
Create a 1D array: [15, 25, 35, 45, 55]. Use boolean indexing to extract elements greater than 30 and print them.

# Expected Output:

[35 45 55]

In [23]:
import numpy as np

arr = np.array([15, 25, 35, 45, 55])
mask = arr > 30

boolean_mask = arr[mask]

print(boolean_mask)

[35 45 55]


Problem #14: Boolean Indexing - Multiple Conditions
Create a 1D array: [10, 20, 30, 40, 50, 60, 70]. Use boolean indexing to extract elements between 25 and 65 (inclusive) and
 print them.

# Expected Output:

[30 40 50 60]

In [38]:
import numpy as np

arr = np.arange(10, 71, 10)

mask =  (arr > 25) & (arr < 65)

bol_mask = arr[mask]
print(bol_mask)

[30 40 50 60]


Problem #15: Boolean Indexing on 2D Arrays
Create a 2D array: [[1, 8, 3], [7, 2, 9], [4, 6, 5]]. Use boolean indexing to extract all elements greater than 5 and
print them as a 1D array.

# Expected Output:

[8 7 9 6]

In [39]:
import numpy as np 

arr = np.array([[1, 8, 3],
                [7, 2, 9],
                [4, 6, 5]])

mask = (arr > 5)

bol_mask = arr[mask]
print(bol_mask)

[8 7 9 6]


Problem #16: Combined Indexing and Slicing
Create a 3x4 array with values 1 to 12. Extract and print the second row, but only the first three elements.

# Expected Output:

[5 6 7]

In [ ]:
import numpy as np 

arr = np.arange(1,13).reshape(3,4)
second_row = arr[1]                   # Indexing
first_3elems = second_row[0:3]        # Slicing

print(first_3elems)

[5 6 7]


Problem #17: Modifying with Indexing
Create a 1D array: [1, 2, 3, 4, 5]. Change the elements at indices 1 and 3 to 99, then print the entire array.

# Expected Output:

[ 1 99  3 99  5]

In [43]:
import numpy as np 

arr = np.arange(1,6)
indices = [1,3]
arr[indices] = 99

print(arr)

[ 1 99  3 99  5]


Problem #18: Boolean Mask Assignment
Create a 1D array: [10, 25, 40, 15, 30]. Using boolean indexing, set all elements less than 20 to 0, then print the array.

# Expected Output:

[ 0 25 40  0 30]

In [45]:
import numpy as np 

arr = np.array([10, 25, 40, 15, 30])
mask = (arr < 20)
arr[mask] = 0

print(arr)

[ 0 25 40  0 30]


Problem #19: Fancy Indexing for Assignment
Create a 1D array of 5 zeros. Using integer array indexing, set elements at indices [1, 3, 4] to 7, then print the array.

# Expected Output:

[0 7 0 7 7]

In [48]:
import numpy as np 

arr_0 = np.zeros(5, dtype = np.int32)
indices = [1, 3, 4]

arr_0[indices] = 7

print(arr_0)

[0 7 0 7 7]


Problem #20: Combined 2D Operations
Create a 3x3 array with values 1 to 9. Extract and print a 2x2 submatrix from the top-right corner.

# Expected Output:

[[2 3]
 [5 6]]

In [1]:
import numpy as np 

arr = np.arange(1,10).reshape(3,3)
arr_sub = arr[:2,1:3]

print(arr_sub)

[[2 3]
 [5 6]]


Part 5 
Date: 11/5/25
Total Problem Solved: 20
Time Spent: 1 hr and 36 mins

Topic Include: Indexing, Slicing, Fancy/Advance Indexing (Integer Indexing and Boolean Array Indexing)

Difficulty: Beginner(20)

START OF INDEXING AND SLICING MODULE --- INTERMEDIATE LEVEL

Problem #1: Strided Access with Negative Steps
Create a 1D array from 0 to 9. Extract elements from index 8 down to 2 with a step of -2 and print the result.

# Expected Output:
[8 6 4 2]

In [8]:
import numpy as np

arr = np.arange(10)
indexs = [x for x in range(8, 1, -2)]

slices = arr[indexs]

print(slices)

[8 6 4 2]


Problem #2: Multi-dimensional Fancy Indexing
Create a 2D array: [[1, 2, 3], [4, 5, 6], [7, 8, 9]]. Use fancy indexing to extract elements at positions (0,0), (1,2), 
and (2,1) as a 1D array.

# Expected Output:
[1 6 8]


In [16]:
import numpy as np 

arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

indexing = arr_2d[[0,1,2], [0,2,1]]

print(indexing)

[1 6 8]


Problem #3: Boolean Indexing with Multiple Conditions
Create a 1D array: [12, 25, 37, 48, 52, 61, 73]. Extract elements that are either less than 30 OR greater than 60 
and print them.

# Expected Output:
[12 25 61 73]

In [18]:
import numpy as np 

arr = np.array([12, 25, 37, 48, 52, 61, 73])

mask = ((arr < 30) | (arr > 60))

print(arr[mask])

[12 25 61 73]


Problem #4: Conditional 2D Submatrix
Create a 4x4 array with values 1 to 16. Extract all elements from rows where the first element of the row is greater than 8.

# Expected Output:
[[ 9 10 11 12]
 [13 14 15 16]]


In [ ]:
import numpy as np

arr = np.arange(1,17).reshape(4,4)

mask = arr[:,0] > 8

print(arr[mask])

[[ 9 10 11 12]
 [13 14 15 16]]
[False False  True  True]


Problem #5: Diagonal Extraction using Fancy Indexing
Create a 3x3 array. Extract the main diagonal elements using coordinate arrays and print as a 1D array.

# Expected Output:
[1 5 9]

In [31]:
import numpy as np 

arr = np.arange(1,10).reshape(3,3)

coor_arr = arr[[0,1,2],[0,1,2]]

print(coor_arr)

[1 5 9]


Problem #6: Modifying with Boolean Masks
Create a 2D array: [[5, 12, 8], [15, 3, 20], [7, 18, 2]]. Set all elements between 10 and 15 (inclusive) to 99 and 
print the modified array.

# Expected Output:
[[ 5 99  8]
 [99  3 20]
 [ 7 99  2]]

In [35]:
import numpy as np 

arr = np.array([[5, 12, 8],
                [15, 3, 20],
                [7, 18, 2]])

arr[(arr >= 10) & (arr <= 15)] = 99

print(arr)

[[ 5 99  8]
 [99  3 20]
 [ 7 18  2]]


Problem #7: Complex Row and Column Selection
Create a 5x5 array with values 1 to 25. Extract rows 1 and 3, but only columns 0, 2, and 4 from those rows.

# Expected Output:
[[ 6  8 10]
 [16 18 20]]

In [43]:
import numpy as np 

arr = np.arange(1,26).reshape(5,5)
rows = arr[[1,3]]
both = rows[:,[0,2,4]]

print(both)

[[ 6  8 10]
 [16 18 20]]


Problem #8: Conditional Replacement with Multiple Criteria
Create a 1D array: [45, 12, 78, 23, 56, 89, 34]. Replace all elements less than 30 with -1 and all elements greater than 70 with 100. 
Print the result.

# Expected Output:
[ 45 -1 100 -1  56 100  34]

In [45]:
import numpy as np 

arr = np.array([45, 12, 78, 23, 56, 89, 34])

lessthan = (arr < 30)
greaterthan = (arr > 70)

arr[lessthan] = -1
arr[greaterthan] = 100

print(arr)


[ 45  -1 100  -1  56 100  34]


Problem #9: Extract Border Elements
Create a 4x4 array. Extract and print all border elements (first/last row and first/last column) as a 1D array.

# Expected Output:
[ 1  2  3  4  5  8  9 12 13 14 15 16]

In [55]:
import numpy as np 

arr = np.arange(1,17).reshape(4,4)

mask = np.zeros(arr.shape, dtype = bool)

mask[0, :] = True
mask[-1, :] = True
mask[:, 0] = True
mask[:,-1] = True 

print(arr[mask])

[ 1  2  3  4  5  8  9 12 13 14 15 16]


Problem #10: Advanced Fancy Indexing with Broadcasting
Create a 3x4 array. Use fancy indexing to extract a 2x2 subarray where row indices are [0, 2] and column indices are [1, 3].

# Expected Output:
[[ 2  4]
 [10 12]]

In [64]:
import numpy as np 

arr = np.arange(1,13).reshape(3,4)
row = arr[[0, 2],:][:, [1,3]]

print(row)

[[ 2  4]
 [10 12]]


Problem #11: Conditional Row Selection
Create a 2D array representing student scores: [[85, 92], [45, 67], [92, 88], [78, 81]]. 
Select all rows where the first score is greater than 70 and print them.

# Expected Output:
[[85 92]
 [92 88]
 [78 81]]

In [66]:
import numpy as np 

arr = np.array([[85, 92],
                [45, 67],
                [92, 88],
                [78, 81]])

mask = arr[:, 0] > 70

print(arr[mask])


[[85 92]
 [92 88]
 [78 81]]


Problem #12: Extract Anti-Diagonal
Create a 3x3 array. Extract the anti-diagonal (top-right to bottom-left) elements and print as a 1D array.

# Expected Output:
[3 5 7]

In [72]:
import numpy as np 

arr = np.arange(1,10).reshape(3,3)

slices = arr[[0,1,2],[-1,-2,-3]]

print(slices)

[3 5 7]


Problem #13: Multi-level Boolean Indexing
Create a 1D array: [10, 25, 40, 15, 30, 45, 20, 35]. Extract elements that are divisible by 5 AND greater than 20, 
then print them.

# Expected Output:
[25 40 30 45 35]

In [73]:
import numpy as np 

arr = np.array([10, 25, 40, 15, 30, 45, 20, 35])

mask = ((arr % 5 == 0) & (arr > 20))

print(arr[mask])

[25 40 30 45 35]


Problem #14: Pattern-based Extraction
Create a 5x5 array with values 1 to 25. Extract every other row starting from row 0, 
and every other column starting from column 1.

# Expected Output:
[[ 2  4]
 [ 7  9]
 [12 14]
 [17 19]
 [22 24]]

In [83]:
import numpy as np 

arr = np.arange(1,26).reshape(5,5)

slices = arr[:, 1::2]

print(slices)

[[ 2  4]
 [ 7  9]
 [12 14]
 [17 19]
 [22 24]]


Problem #15: Conditional Column Modification
Create a 3x4 array. Set all elements in the second column to 0 if any element in that column is greater than 10. 
Print the modified array.

# Expected Output:
[[ 1  0  3  4]
 [ 5  0  7  8]
 [ 9  0 11 12]]


In [103]:
import numpy as np 

arr = np.arange(1,13).reshape(3,4)

if (arr[:,1] >= 10).any(axis=0):
    arr[:,1] = 0

print(arr)

[[ 1  0  3  4]
 [ 5  0  7  8]
 [ 9  0 11 12]]


Part 6 
Date: 11/7/25
Total Problem Solved: 15
Time Spent: 2 hr and 26 mins

Topic Include: Indexing, Slicing, Fancy/Advance Indexing (Integer Indexing and Boolean Array Indexing)

Difficulty: Intermediate(15)

Problem #16: Extract Fibonacci Pattern
Create a 1D array with first 10 Fibonacci numbers: [0, 1, 1, 2, 3, 5, 8, 13, 21, 34]. 
Extract numbers that are at prime indices and greater than 5.

# Expected Output:
[13]

In [ ]:
import numpy as np 

lists = []
prev = 0
curr = 1

for _ in range(10):

    lists.append(prev)

    prev, curr = curr, prev + curr

arr = np.array(lists, dtype = np.int32)
mask = (arr)

# For Identifying PRIME

def is_prime(n: int):
    if n < 2:
        return False
    if n == 2:
        return True
    if n % 2 == 0:
        return False
    r = int(n**0.5) + 1
    for i in range(3, r, 2):
        if n % i == 0:
            return False
    return True

indices = np.arange(arr.size)
prime_index_mask = np.array([is_prime(i) for i in indices])
result = arr[prime_index_mask & (arr > 5)]

print(result)

[13]


Problem #17: Multi-dimensional Conditional Selection
Create a 3x3x3 array with values 1 to 27. Extract all elements from the second "layer" (index 1) where values are multiples of 3.

# Expected Output:
[12 15 18 21 24 27]

In [ ]:
import numpy as np 
arr = np.arange(1,28).reshape(3,3,3)

first_slice = arr[1:]
mask = (first_slice % 3 == 0)
print(first_slice[mask])

[12 15 18 21 24 27]


Problem #18: Extract Elements with Unique Properties
Create a 1D array: [12, 25, 36, 49, 64, 81, 100]. Extract perfect squares that are also even numbers.

# Expected Output:
[36 64 100]

In [ ]:
import numpy as np

arr = np.array([12, 25, 36, 49, 64, 81, 100])
even_squares = []

for x in arr:
    root = int(np.sqrt(x))
    even_squares.append(root * root == x and root % 2 == 0)

perfect_squares = (arr[even_squares]) 

print(perfect_squares)

[ 36  64 100]


Problem #19: Pattern-based Row Selection
Create a 6x4 array with values 1 to 24. Select rows where the sum of the row is a prime number.

# Expected Output:
[[ 5  6  7  8]
 [17 18 19 20]]

In [ ]:
import numpy as np 

arr = np.arange(1,25).reshape(6,4)
sums_row = arr.sum(axis=1)
# Prime Finder Function
def is_prime(n: int):
    if n < 2:
        return False
    if n == 2:
        return True
    if n % 2 == 0:
        return False
    r = int(n**0.5) + 1
    for i in range(3, r, 2):
        if n % i == 0:
            return False
    return True

prime = np.array([is_prime(i) for i in sums_row])
result = arr[prime]

print(result)
#THE OUTPUT AND PROBLEM DESCRIPTION IS NOT ALIGN CORRECTLY

[]


Problem #20: Extract Alternating Triangles
Create a 5x5 array with values 1 to 25. Extract elements from the upper triangle (above main diagonal) with even values only.

# Expected Output:
[2  4  8 10 14 20]

In [ ]:
import numpy as np 

arr = np.arange(1, 26).reshape(5,5)
upper_triangle = np.triu(np.ones((5,5),dtype=bool), k = 1)
even_result = arr[upper_triangle & (arr % 2 == 0)]

print(arr)
print(even_result)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[ 2  4  8 10 14 20]


START OF INDEXING AND SLICING ADVANCE LEVEL

Problem #1: Extract Checkerboard Pattern
Create a 4x4 array with values 1 to 16. Extract elements where the sum of row and column indices is odd, 
creating a checkerboard pattern starting with the second element.

# Expected Output:
[ 2  4  5  7 10 12 13 15]

In [ ]:
import numpy as np 

arr = np.arange(1,17).reshape(4,4)

odd_sum_indices = []

for x in range(4):
    for y in range(4):
        if (x + y) % 2 != 0:
            odd_sum_indices.append((x, y))

row  = np.array([pair[0] for pair in odd_sum_indices])
column  = np.array([pair[1] for pair in odd_sum_indices])

result = arr[row,column]

print(result)

[ 2  4  5  7 10 12 13 15]


Problem #2: Conditional Row Selection
Create a 3x4 array with values 1 to 12. Extract rows where the sum of the row is greater than 20.

# Expected Output:
[[ 5  6  7  8]
 [ 9 10 11 12]]

In [102]:
import numpy as np 

arr = np.arange(1,13).reshape(3,4)

sum_row = arr.sum(axis=1) > 20
rows = arr[sum_row]
print(rows)

[[ 5  6  7  8]
 [ 9 10 11 12]]


Problem #3: Extract Multiple Diagonals
Create a 4x4 array with values 1 to 16. Extract both the main diagonal and the diagonal immediately above it 
as separate 1D array.

# Expected Output:
Main diagonal: [ 1  6 11 16]
Upper diagonal: [ 2  7 12]

In [ ]:
import numpy as np 

arr = np.arange(1, 17).reshape(4,4)

main_dia = arr[[0,1,2,3],[0,1,2,3]]
upper_dia = np.diag(arr, k = 1)

print(main_dia)
print(upper_dia)

[ 1  6 11 16]
[ 2  7 12]


Problem #4: Replace Based on Neighbor Values
Create a 1D array: [3, 8, 2, 9, 5, 7, 1, 6]. Replace all elements that are greater than both their immediate neighbors with 99. 
(Ignore first and last elements since they don't have two neighbors)

# Expected Output:
[ 3 99  2 99  5  7  1  6]

In [ ]:
import numpy as np 

arr = np.array([3, 8, 2, 9, 5, 7, 1, 6])
              #[0, 1, 2, 3, 4, 5, 6, 7]
mask = []

for x in range(len(arr)):

    if x == 0 or x == (len(arr) - 1):
        mask.append(False)

    else:
        if x != (len(arr)-1):
            if arr[x] > arr[x+1]:
                mask.append(True)
            else:
                mask.append(False)

arr[mask] = 99 

print(arr)

[ 3 99  2 99  5 99  1  6]


Problem #5: Extract Border Elements
Create a 5x5 array with values 1 to 25. Extract all border elements in clockwise order starting from top-left.

# Expected Output:
[ 1  2  3  4  5 10 15 20 25 24 23 22 21 16 11  6]

In [168]:
import numpy as np 

arr = np.arange(1, 26).reshape(5,5)
first = arr[0, :]
second = arr[1:,-1]
third = arr[-1,3:0:-1]
fourth = arr[4:0:-1,0]

result = np.concatenate((first, second, third, fourth))

print(result)

[ 1  2  3  4  5 10 15 20 25 24 23 22 21 16 11  6]


Part 7 
Date: 11/10/25
Total Problem Solved: 10
Time Spent: 3 hr and 31 mins

Topic Include: Indexing, Slicing, Fancy/Advance Indexing (Integer Indexing and Boolean Array Indexing)

Difficulty: Intermediate(5), Advance(5)