DOUBLE CLICK THE PROBLEM CELL TO SEE THE CORRECT FORMAT OF THE PROBLEM AND EXPECTED OUTPUT

Start of Advance Array Operations - MODULE 5

Beginner Level 

Problem #1: Basic Axis Swapping
Create a 2x3 array with values 1-6. Swap the axes (transpose) and print both original and swapped arrays.

# Expected Output:
Original:
[[1 2 3]
 [4 5 6]]
Swapped:
[[1 4]
 [2 5]
 [3 6]]

In [1]:
import numpy as np 

arr = np.arange(1, 7).reshape(2,3)

trans_arr = np.transpose(arr)

print(f"Original: \n {arr}")
print(f"Swapped: \n {trans_arr}")

Original: 
 [[1 2 3]
 [4 5 6]]
Swapped: 
 [[1 4]
 [2 5]
 [3 6]]


Problem #2: Simple Array Filtering
Create a 1D array: [10, 25, 30, 45, 50, 65]. Filter to keep only elements greater than 35.

# Expected Output:
[45 50 65]

In [2]:
import numpy as np 

arr = np.array([10, 25, 30, 45, 50, 65])

mask_filter = arr > 35

filters = arr[mask_filter]

print(filters)

[45 50 65]


Problem #3: Vertical Array Joining
Create two 2x3 arrays: [[1, 2, 3], [4, 5, 6]] and [[7, 8, 9], [10, 11, 12]]. Join them vertically.

# Expected Output:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

In [5]:
import numpy as np 

arr = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])

vertical_join = np.vstack((arr,arr2))

print(vertical_join)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


Problem #4: Horizontal Array Joining
Using the same arrays from Problem #3, join them horizontally.

# Expected Output:
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [6]:
import numpy as np 

arr = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])

horiz_join = np.hstack((arr, arr2))

print(horiz_join)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


Problem #5: Basic Array Sorting
Create a 1D array: [34, 12, 67, 23, 89, 45]. Sort the array in ascending order.

# Expected Output:
[12 23 34 45 67 89]

In [10]:
import numpy as np 

arr = np.array([34, 12, 67, 23, 89, 45])

sort_arr = np.sort(arr)

print(sort_arr)

[12 23 34 45 67 89]


Problem #6: Searching for Values
Create an array: [10, 20, 30, 40, 50]. Find the index of the value 30.

# Expected Output:
2

In [18]:
import numpy as np 

arr = np.arange(10, 51, 10)

tryy = np.argmax(arr == 30)

print(tryy)

2


Problem #7: Finding Unique Elements
Create an array: [1, 2, 2, 3, 1, 4, 3, 5]. Find all unique elements.

# Expected Output:
[1 2 3 4 5]

In [19]:
import numpy as np 

arr = np.array([1, 2, 2, 3, 1, 4, 3, 5])

unique_items = np.unique(arr)

print(unique_items)

[1 2 3 4 5]


Problem #8: Creating DateTime Array
Create a datetime array for January 1-5, 2023 using np.arange with datetime64.

# Expected Output:
['2023-01-01' '2023-01-02' '2023-01-03' '2023-01-04' '2023-01-05']

In [21]:
import numpy as np 

date_arr = np.array(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04', '2023-01-05'], dtype = 'datetime64')

print(date_arr)

['2023-01-01' '2023-01-02' '2023-01-03' '2023-01-04' '2023-01-05']


Problem #9: Filtering with Boolean Conditions
Create an array: [15, 25, 35, 45, 55]. Create a boolean mask for elements between 20 and 50 (inclusive).

# Expected Output:
[False  True  True  True False]


In [23]:
import numpy as np 

arr = np.arange(15, 56, 10)

mask = ((arr > 20) & (arr < 51))

print(mask)

[False  True  True  True False]


Problem #10: Multi-dimensional Sorting
Create a 2D array: [[30, 10], [20, 40], [10, 30]]. Sort by the first column.

# Expected Output:
[[10 30]
 [20 40]
 [30 10]]

In [37]:
import numpy as np 

arr = np.array([[30, 10], 
                [20, 40], 
                [10, 30]])

first_column = arr[:, 0]

sort_colums = np.argsort(first_column)

print(arr[sort_colums])

[[10 30]
 [20 40]
 [30 10]]


Problem #11: Searching with Conditions
Create an array: [5, 12, 8, 15, 3, 20]. Find indices where elements are greater than 10.

# Expected Output:
[1 3 5]

In [39]:
import numpy as np 

arr = np.array([5, 12, 8, 15, 3, 20])

indx = np.where(arr > 10)[0]

print(indx)

[1 3 5]


Problem #12: Finding Unique Rows
Create a 2D array: [[1, 2], [3, 4], [1, 2], [5, 6]]. Find all unique rows.

# Expected Output:
[[1 2]
 [3 4]
 [5 6]]

In [44]:
import numpy as np 

arr = np.array([[1, 2], 
                [3, 4], 
                [1, 2], 
                [5, 6]])

unique_rows = np.unique(arr, axis = 0)

print(unique_rows)

[[1 2]
 [3 4]
 [5 6]]


Problem #13: DateTime Array with Steps
Create a datetime array for every other day from January 1 to January 7, 2023.

# Expected Output:
['2023-01-01' '2023-01-03' '2023-01-05' '2023-01-07']

In [51]:
import numpy as np 

arr = np.array([f'2023-01-0{x}' for x in range(1, 8, 2)], dtype = 'datetime64')

print(arr)

['2023-01-01' '2023-01-03' '2023-01-05' '2023-01-07']


Problem #14: Axis Swapping with 3D Array
Create a 2x2x3 array with values 1-12. Swap axes 0 and 1, then print the new shape.

# Expected Output:
Original shape: (2, 2, 3)
After swap: (2, 2, 3)  # Same shape but different memory layout

In [60]:
import numpy as np 

arr = np.arange(1, 13).reshape(2,2,3)

swaps = np.swapaxes(arr, 0, 1)

print(f"Original shape and strides: {arr.shape}, {arr.strides}")
print(f"After swap shape and strides: {swaps.shape}, {swaps.strides} # Same shape but different memory layout")

Original shape and strides: (2, 2, 3), (48, 24, 8)
After swap shape and strides: (2, 2, 3), (24, 48, 8) # Same shape but different memory layout


Problem #15: Complex Filtering
Create an array: [12, 25, 38, 41, 57, 63]. Filter to keep elements that are even AND greater than 30.

# Expected Output:
[38]

In [61]:
import numpy as np 

arr = np.array([12, 25, 38, 41, 57, 63])

com_filters = ((arr % 2 == 0) & (arr > 30))

print(arr[com_filters])

[38]


Problem #16: Stacking Arrays
Create three 1D arrays: [1, 2], [3, 4], [5, 6]. Stack them vertically to create a 3x2 array.

# Expected Output:
[[1 2]
 [3 4]
 [5 6]]

In [62]:
import numpy as np 

arr = np.array([1, 2])
arr2 = np.array([3, 4])
arr3 = np.array([5, 6])

vertical_stack = np.vstack((arr, arr2, arr3))

print(vertical_stack)

[[1 2]
 [3 4]
 [5 6]]


Problem #17: Sorting with Axis Parameter
Create a 2D array: [[30, 10, 20], [15, 25, 5]]. Sort along axis 1 (rows).

# Expected Output:
[[10 20 30]
 [ 5 15 25]]


In [ ]:
import numpy as np

arr = np.array([[30, 10, 20], 
                [15, 25, 5]])

sort_axis1 = np.sort(arr, axis = 1)

print(sort_axis1)

[[10 20 30]
 [ 5 15 25]]


Problem #18: Finding Maximum and Its Index
Create an array: [45, 23, 67, 12, 89, 34]. Find the maximum value and its index.

# Expected Output:
Maximum value: 89
Index: 4

In [65]:
import numpy as np 

arr = np.array([45, 23, 67, 12, 89, 34])

max_value_indx = np.argmax(arr)
max_value = arr[max_value_indx]

print(f"""Maximum value: {max_value}
Index: {max_value_indx}""")

Maximum value: 89
Index: 4


Problem #19: DateTime Range with Frequency
Create a datetime array for the first 5 hours of January 1, 2023, with hourly frequency.

# Expected Output:
['2023-01-01T00' '2023-01-01T01' '2023-01-01T02' '2023-01-01T03' '2023-01-01T04']


In [67]:
import numpy as np

date_arange = np.arange('2023-01-01T00', '2023-01-01T05', dtype = 'datetime64[h]')

print(date_arange)

['2023-01-01T00' '2023-01-01T01' '2023-01-01T02' '2023-01-01T03'
 '2023-01-01T04']


Problem #20: Comprehensive Array Operations
Create an array [5, 2, 5, 8, 2, 9]. Filter to keep values greater than 4, find unique values, sort them, and then concatenate with [1, 2, 3].

# Expected Output:
Filtered (>4): [5, 5, 8, 9]
Unique: [5, 8, 9]
Sorted: [5, 8, 9]
Final concatenated: [5, 8, 9, 1, 2, 3]


In [72]:
import numpy as np

arr = np.array([5, 2, 5, 8, 2, 9])
conct_arr = np.array([1, 2, 3])

filter_4 = arr[np.where(arr > 4)]
unique_values = np.unique(filter_4)
sorting = np.sort(unique_values)
final_concate = np.concatenate((sorting, conct_arr))

print(f"""Filtered (>4): {filter_4}
Unique: {unique_values}
Sorted: {sorting}
Final concatenated: {final_concate}""")

Filtered (>4): [5 5 8 9]
Unique: [5 8 9]
Sorted: [5 8 9]
Final concatenated: [5 8 9 1 2 3]


Part 14 
Date: 11/30/25
Total Problem Solved: 20
Time Spent: 2 hr and 4 mins

Topic Include: Advance Array Operations (Swapping Axes, Filtering, Joining, Sort, Counting, Searching, Unique Values, Datetime Arrays)

Difficulty: Beginner(20)