Problem #1: The Fundamental Array

Create a 1-dimensional NumPy array from the Python list [1, 2, 3, 4, 5] and print it.

Expected Output:

[1 2 3 4 5]

Solution Below:

In [ ]:
import numpy as np 

a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


Problem #2: A Line of Zeroes

Create a 1D array of length 10 where every element is 0 and print it.

Expected Output:

[0 0 0 0 0 0 0 0 0 0]

Solution Below

In [3]:
import numpy as np

a = np.full(10,0)
print(a)

[0 0 0 0 0 0 0 0 0 0]


Problem #3: The Identity Matrix

Create a 3x3 identity matrix (2D array) and print it.

Expected Output:

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

 Solution Below:

In [9]:
import numpy as np

a = np.array([[1.,0.,0.],[0.,1.,0.],[0.,0.,1.]])
print(a)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Problem #4: A Range of Numbers

Create a 1D array containing the numbers from 10 to 25 (inclusive) and print it.

Expected Output:

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25]

Solution Below:

In [10]:
import numpy as np

array = np.arange(10,26)
print(array)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25]


Problem #5: Check the Type

Create a 1D array from the list [1.5, 2.5, 3.5]. Print the array and then print its data type (dtype).

Expected Output:

[1.5 2.5 3.5]
float64

Solution Below:

In [11]:
import numpy as np

array = np.array([1.5, 2.5, 3.5])
print(array)
print(array.dtype)

[1.5 2.5 3.5]
float64


Problem #6: Forcing a Type

Create a 1D array from the list [1, 2, 3, 4] but explicitly set the data type to float32. Print the array and its dtype.

Expected Output:

[1. 2. 3. 4.]
float32

Solution Below:

In [16]:
import numpy as np

array = np.array([1,2,3,4], dtype = np.float32)

print(array)
print(array.dtype)


[1. 2. 3. 4.]
float32


Problem #7: A Square of Sequential Integers

Create a 1D array with elements from 1 to 9, then reshape it into a 3x3 matrix. Print the new 2D array.

Expected Output:

[[1 2 3]
 [4 5 6]
 [7 8 9]]

Solution Below:

In [17]:
import numpy as np

array = np.arange(1,10).reshape(3,3)

print(array)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


Problem #8: The Transpose
Create a 2x4 array from a range of 8 numbers, reshape it, and then print its transpose.

Expected Output (Original 2x4):

[[0 1 2 3]
 [4 5 6 7]]

Expected Output (Transpose):

[[0 4]
 [1 5]
 [2 6]
 [3 7]]

Solution Below:

In [21]:
import numpy as np 

array = np.arange(8).reshape(2,4)

transposed_array =  np.transpose(array)

print(array, "\n")
print(transposed_array)

[[0 1 2 3]
 [4 5 6 7]] 

[[0 4]
 [1 5]
 [2 6]
 [3 7]]


Problem #9: Flatten it Out

Create a 2x3 array and then flatten it (convert it to a 1D array). Print both the original and the flattened array.

Expected Output (Original):

[[10 20 30]
 [40 50 60]]

Expected Output (Flattened):

[10 20 30 40 50 60]

Solution Below:

In [26]:
import numpy as np 

array = np.arange(10,61,10).reshape(2,3)
print(array,"\n")

flatten_array = array.flatten()
print(flatten_array)

[[10 20 30]
 [40 50 60]] 

[10 20 30 40 50 60]


Problem #10: A Diagonal Line

Create a 1D array with [5, 6, 7, 8] and then convert it into a 2D array with 4 rows and 1 column. Print the result.

Expected Output:

[[5]
 [6]
 [7]
 [8]]

Solution Below:

In [27]:
import numpy as np 

array = np.array([5,6,7,8]).reshape(4,1)
print(array)

[[5]
 [6]
 [7]
 [8]]


Problem #11: Stacking Vertically

Create two 1D arrays: a = [1, 2, 3] and b = [4, 5, 6]. Stack them vertically to form a 2x3 array and print it.

Expected Output:

[[1 2 3]
 [4 5 6]]

Solution Below:

In [28]:
import numpy as np

array_1 = np.array([1 ,2, 3])
array_2 = np.array([4, 5, 6])

array_3 = np.concatenate((array_1, array_2)).reshape(2,3)
print(array_3)

[[1 2 3]
 [4 5 6]]


Problem #12: Stacking Horizontally

Using the same arrays a and b from the previous problem, stack them horizontally to form a 1x6 array and print it.

Expected Output:

[1 2 3 4 5 6]

Solution Below:

In [35]:
array_1 = np.array([1, 2, 3])
array_2 = np.array([4, 5, 6])
array_3 = np.concatenate((array_1, array_2))

print(array_3)

[1 2 3 4 5 6]


Problem #13: A Constant Matrix

Create a 2x5 array filled entirely with the number 7 and print it.

Expected Output:

[[7 7 7 7 7]
 [7 7 7 7 7]]

Solution Below:

In [37]:
seven_array = np.full((2,5),7)
print(seven_array)

[[7 7 7 7 7]
 [7 7 7 7 7]]


Problem #14: Evenly Spaced Intervals

Create a 1D array of 5 evenly spaced numbers between 0 and 1 (inclusive) and print it.

Expected Output:

[0.   0.25 0.5  0.75 1.  ]

Solution Below:

In [38]:
linspace = np.linspace(0,1,num = 5)
print(linspace)

[0.   0.25 0.5  0.75 1.  ]


Problem #15: The Shape of Things
Create a 2D array with 2 rows and 4 columns from a range of 8 numbers. Print the array and then print its shape.

Expected Output (Array):

[[0 1 2 3]
 [4 5 6 7]]

Expected Output (Shape):

(2, 4)

Solution Below:

In [40]:
array = np.arange(8).reshape(2,4)

print(array,"\n")
print(array.shape)

[[0 1 2 3]
 [4 5 6 7]] 

(2, 4)


Part 1 
Date: 10/27/25
Total Problem Solved: 15
Time Spent: 1 hr and 2 mins

Topic Include: ndarray object, Data Types (dtype), Array Creation Routines, Array Manipulation.
Difficulty: Beginner