# DOUBLE CLICK THE PROBLEM CELL TO SEE THE CORRECT FORMAT OF THE PROBLEM AND EXPECTED OUTPUT

Start of Idenxing and Slicing Module

Problem #1: Basic 1D Indexing
Create a 1D array with values [10, 20, 30, 40, 50]. Access and print the third element (index 2).

# Expected Output:

30

In [2]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
print(arr[2])

30


Problem #2: Negative Indexing
Using the same array from Problem #1, access and print the last element using negative indexing.

# Expected Output:

50


In [3]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50])
print(arr1[-1])

50


Problem #3: Basic 1D Slicing
Create a 1D array with values [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]. Slice and print elements from index 3 to 7 
(inclusive of 3, exclusive of 7).

# Expected Output:

[3 4 5 6]

In [4]:
import numpy as np

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

slices = arr[3:7]
print(slices)

[3 4 5 6]


Problem #4: Slicing with Steps
Using the same array from Problem #3, slice and print every second element from the entire array.

# Expected Output:

[0 2 4 6 8]

In [5]:
import numpy as np

arr1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

second_elem = arr1[::2]

print(second_elem)

[0 2 4 6 8]


Problem #5: Reverse Array with Slicing
Using the same array from Problem #3, slice and print the array in reverse order.

# Expected Output:

[9 8 7 6 5 4 3 2 1 0]

In [7]:
import numpy as np

arr2 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

reverse_arr2 = arr2[::-1]
print(reverse_arr2)

[9 8 7 6 5 4 3 2 1 0]


Problem #6: 2D Array Indexing
Create a 2D array: [[1, 2, 3], [4, 5, 6], [7, 8, 9]]. Access and print the element at row 1, column 2.

# Expected Output:

6

In [8]:
import numpy as np

arr_2d = np.array([[1, 2, 3], 
                   [4, 5, 6], 
                   [7, 8, 9]])

print(arr_2d[1,2])

6


Problem #7: 2D Array Slicing
Using the same array from Problem #6, slice and print the first two rows and all columns.

# Expected Output:

[[1 2 3]
 [4 5 6]]

In [11]:
import numpy as np

arr_2 = np.array([[1, 2, 3], 
                   [4, 5, 6], 
                   [7, 8, 9]])

two_r_all_colms = arr_2[:2,:]

print(two_r_all_colms)

[[1 2 3]
 [4 5 6]]


Problem #8: Column Slicing
Using the same array from Problem #6, slice and print the second column (index 1) from all rows.

# Expected Output:

[2 5 8]

In [13]:
import numpy as np

arr_22 = np.array([[1, 2, 3], 
                   [4, 5, 6], 
                   [7, 8, 9]])

sec_colms_all_rows = arr_22[:,1]
print(sec_colms_all_rows)

[2 5 8]


Problem #9: Submatrix Extraction
Create a 4x4 array with values 0 to 15: [[0,1,2,3], [4,5,6,7], [8,9,10,11], [12,13,14,15]]. 
Extract and print the center 2x2 submatrix.

# Expected Output:

[[5 6]
 [9 10]]

In [17]:
import numpy as np

arr = np.arange(16).reshape(4,4)

center_submatrix = arr[1:3,1:3]
print(center_submatrix)

[[ 5  6]
 [ 9 10]]


Problem #10: Slicing with Start/End/Step
Create a 1D array from 0 to 19. Extract and print elements from index 5 to 15 with step 3.

# Expected Output:

[ 5  8 11 14]

In [19]:
import numpy as np

arr = np.arange(20)

slices = arr[5: 16: 3]
print(slices)

[ 5  8 11 14]


Problem #11: Integer Array Indexing (Fancy Indexing)
Create a 1D array: [100, 200, 300, 400, 500]. Use integer array indexing to extract elements at indices [0, 2, 4] and 
print them.

# Expected Output:

[100 300 500]

In [20]:
import numpy as np

arr = np.array([100, 200, 300, 400, 500])
indices = [0, 2, 4]

int_index = arr[indices]

print(int_index)

[100 300 500]


Problem #12: 2D Fancy Indexing
Create a 2D array: [[1, 2], [3, 4], [5, 6], [7, 8]]. Use fancy indexing to extract rows at indices [0, 2, 3] and
 print the result.

# Expected Output:

[[1 2]
 [5 6]
 [7 8]]

In [22]:
import numpy as np

arr_2d = np.arange(1,9).reshape(4,2)
indices = [0, 2, 3]

int_indx = arr_2d[indices]

print(int_indx)

[[1 2]
 [5 6]
 [7 8]]


Problem #13: Boolean Indexing - Basic
Create a 1D array: [15, 25, 35, 45, 55]. Use boolean indexing to extract elements greater than 30 and print them.

# Expected Output:

[35 45 55]

In [23]:
import numpy as np

arr = np.array([15, 25, 35, 45, 55])
mask = arr > 30

boolean_mask = arr[mask]

print(boolean_mask)

[35 45 55]


Problem #14: Boolean Indexing - Multiple Conditions
Create a 1D array: [10, 20, 30, 40, 50, 60, 70]. Use boolean indexing to extract elements between 25 and 65 (inclusive) and
 print them.

# Expected Output:

[30 40 50 60]

In [38]:
import numpy as np

arr = np.arange(10, 71, 10)

mask =  (arr > 25) & (arr < 65)

bol_mask = arr[mask]
print(bol_mask)

[30 40 50 60]


Problem #15: Boolean Indexing on 2D Arrays
Create a 2D array: [[1, 8, 3], [7, 2, 9], [4, 6, 5]]. Use boolean indexing to extract all elements greater than 5 and
print them as a 1D array.

# Expected Output:

[8 7 9 6]

In [39]:
import numpy as np 

arr = np.array([[1, 8, 3],
                [7, 2, 9],
                [4, 6, 5]])

mask = (arr > 5)

bol_mask = arr[mask]
print(bol_mask)

[8 7 9 6]


Problem #16: Combined Indexing and Slicing
Create a 3x4 array with values 1 to 12. Extract and print the second row, but only the first three elements.

# Expected Output:

[5 6 7]

In [ ]:
import numpy as np 

arr = np.arange(1,13).reshape(3,4)
second_row = arr[1]                   # Indexing
first_3elems = second_row[0:3]        # Slicing

print(first_3elems)

[5 6 7]


Problem #17: Modifying with Indexing
Create a 1D array: [1, 2, 3, 4, 5]. Change the elements at indices 1 and 3 to 99, then print the entire array.

# Expected Output:

[ 1 99  3 99  5]

In [43]:
import numpy as np 

arr = np.arange(1,6)
indices = [1,3]
arr[indices] = 99

print(arr)

[ 1 99  3 99  5]


Problem #18: Boolean Mask Assignment
Create a 1D array: [10, 25, 40, 15, 30]. Using boolean indexing, set all elements less than 20 to 0, then print the array.

# Expected Output:

[ 0 25 40  0 30]

In [45]:
import numpy as np 

arr = np.array([10, 25, 40, 15, 30])
mask = (arr < 20)
arr[mask] = 0

print(arr)

[ 0 25 40  0 30]


Problem #19: Fancy Indexing for Assignment
Create a 1D array of 5 zeros. Using integer array indexing, set elements at indices [1, 3, 4] to 7, then print the array.

# Expected Output:

[0 7 0 7 7]

In [48]:
import numpy as np 

arr_0 = np.zeros(5, dtype = np.int32)
indices = [1, 3, 4]

arr_0[indices] = 7

print(arr_0)

[0 7 0 7 7]


Problem #20: Combined 2D Operations
Create a 3x3 array with values 1 to 9. Extract and print a 2x2 submatrix from the top-right corner.

# Expected Output:

[[2 3]
 [5 6]]

In [51]:
import numpy as np 

arr = np.arange(1,10).reshape(3,3)
arr_sub = arr[:2,1:3]

print(arr_sub)

[[2 3]
 [5 6]]


Part 5 
Date: 11/5/25
Total Problem Solved: 20
Time Spent: 1 hr and 36 mins

Topic Include: Indexing, Slicing, Fancy/Advance Indexing (Integer Indexing and Boolean Array Indexing)

Difficulty: Beginner(20)